function IAUnit(){}
IAUnit.prototype={getmaneuver:function(){var a,e,b=[],c=[],f=[],g=this.getdial();for(a=0;a<squadron.length;a++)if(squadron[a].team!=this.team){var h=squadron[a],k=h.getdial();for(e=0;e<k.length;e++)b.push(h.getOutlinePoints(h.getpathmatrix(h.m.clone(),k[e].move)))}for(a=0;a<g.length;a++){h=0;e=this.m.clone();g[a].move.match(/K\d|SL\d|SR\d/)&&(e=e.add(MR(180,0,0)));var k=this.getpathmatrix(e,g[a].move),l=!1;this.isinzone(k)||(l=!0);if(!l){var m=this.getOutline(k);for(e=0;e<OBSTACLES.length;e++)if(this.isintersecting(OBSTACLES[e].getOutlinePoints(),m)){l=
!0;break}m.remove()}if(!l){f.push(a);k=this.getSectorString(3,k);for(e=0;e<b.length;e++)this.isintersecting(b[e],k)&&h++;0<h&&c.push({n:h,m:a})}}if(0<c.length)c.sort(function(a,b){return b.n-a.n}),a=c[0].m;else{for(a=0;a<f.length&&!g[f[a]].move.match(/F\d/);a++);a==f.length&&(a=0);a=f[a]}return a},freeaction:function(a){a()},resolveactionselection:function(a,e){e(0)},resolveactionmove:function(a,e,b,c){var f=[],g=!1;for(b=0;b<a.length;b++)f[b]=this.getpossibleoutline(a[b]),f[b].ol.remove();for(b=
0;b<a.length;b++)if(f[b].b||c){g=!0;break}g?(this.m=a[b],e(this,b)):e(this,-1)},beginplanningphase:function(){if(-1==this.maneuver)var a=setInterval(function(){this.maneuver=this.getmaneuver();nextstep();clearInterval(a)}.bind(this),200)},timetoshowmaneuver:function(){return-1<this.maneuver&&phase==ACTIVATION_PHASE},showdial:function(){$("#move").css({display:"none"});$("#maneuverdial").empty();if(phase>PLANNING_PHASE)if(-1==this.maneuver||this.hasmoved)this.dialspeed.attr({text:""}),this.dialdirection.attr({text:""});
else{d=this.getdial()[this.maneuver];var a=C[d.difficulty];activeunit!=this&&(a=halftone(a));this.dialspeed.attr({text:P[d.move].speed,fill:a});this.dialdirection.attr({text:P[d.move].key,fill:a})}},beginactivation:function(){this.resolvemaneuver()},showactivation:function(){$("#activationdial").empty();this.timeformaneuver()&&this.resolvemaneuver()},endmaneuver:function(){this.ionized=0;this.action=-1;this.updateactionlist();$("#actiondial").empty();this.canuncloak();if(this.candoaction()&&!this.actiondone){this.actiondone=
!0;var a=this.actionList.indexOf("FOCUS"),e=this.actionList.indexOf("EVADE");-1<a&&this.candofocus()?(this.actionsdone.push("FOCUS"),this.addfocus()):-1<e&&this.candoevade()?(this.actionsdone.push("EVADE"),this.addevade()):this.endaction()}else this.endaction()},showaction:function(){$("#actiondial").empty();this.updateactionlist();if(this.action<this.actionList.length&&-1<this.action){var a=A[this.actionList[this.action]].color;this.actionicon.attr({fill:this==activeunit?a:halftone(a)})}else this.actionicon.attr({text:""})},
selecttargetforattack:function(a){var e=this.weapons[a].getrangeallunits(),b,c=[];for(b=0;b<e.length;b++)e[b].team!=this.team&&c.push(e[b]);if(0==c.length)return!1;this.declareattack(a,c[0]);this.resolveattack(a,c[0]);return!0},beginattack:function(){var a=[],e,b,c;if(this.canfire()){var f=this.gethitrangeallunits();for(e=1;3>=e;e++)for(b=0;b<f[e].length;b++)for(c=0;c<f[e][b].wp.length;c++){var g=f[e][b].wp[c];-1==a.indexOf(g)&&a.push(g)}this.selecttargetforattack(a[0])}},showattack:function(){$("#attackdial").empty()},
getusabletokens:function(a,e){var b="",c="",c="";0<this.focus&&(b+="<td title='"+this.focus+" focus token(s)' class='xfocustoken'></td>");0<this.evade&&(b+="<td title='"+this.evade+" evade token(s)' class='xevadetoken'></td>");for(var f=0;f<this.targeting.length;f++)c+=this.targeting[f].name+" ";""!=c&&(b+="<td title='targeting "+c.replace(/\'/g,"&#39;")+"' class='xtargettoken'></td>");c="";for(f=0;f<this.istargeted.length;f++)c+=this.istargeted[f].name+" ";""!=c&&(b+="<td title='targeted by "+c.replace(/\'/g,
"&#39;")+"' class='xtargetedtoken'></td>");0<this.stress&&(b+="<td title='"+this.stress+" stress token(s)' class='xstresstoken'></td>");0<this.ionized&&(b+="<td title='"+this.ionized+" ionization token(s)' class='xionizedtoken'></td>");return b},attackroll:function(a){var e,b,c,f,g=this.getattacktable(a),h=0,k=Math.random();for(b=0;b<=a;b++)for(c=0;c<=a-b;c++)for(f=0;f<=a-b-c;f++)if(e=100*b+c+10*f,h+=g[e],h>k)return this.canusefocus()&&0<b?(this.usefocus(),10*f+c+b):100*b+10*f+c;return 0},defenseroll:function(a){var e,
b,c,f=this.getdefensetable(a),g=0,h=Math.random();if(0==a)return 0;for(c=0;c<=a;c++)for(b=0;b<=a-c;b++)if(e=10*c+b,g+=f[e],g>h)return this.canuseevade()&&(this.useevade(),b++),this.canusefocus()?c+b:10*c+b;return 0}};
