var REBEL="Rebel Alliance",EMPIRE="Galactic Empire",SCUM="Scum and Villainy";function Pilot(a){var b,c=PILOT_dict[a];for(b=0;b<PILOTS.length;b++)if(PILOTS[b].name==c)return Pilotfromid(b);console.log("Could not find pilot "+a)}function Pilotfromid(a){a=new Unit(PILOTS[a]);a.id=name;a.unique||(a.id=""+a.id+globalid++);void 0!=a.init&&a.init();return a}
var PILOTS=[{name:"Wedge Antilles",done:!0,unique:!0,faction:"REBEL",unit:"X-Wing",skill:9,init:function(){var a=Unit.prototype.getdefensestrength;Unit.prototype.getdefensestrength=function(b,c){var d=a.call(this,b,c);return"Wedge Antilles"==c.name&&0<d?(log("["+c.name+"] defense reduced from "+d+" to "+(d-1)+" for "+this.name),d-1):d}},points:29,upgrades:["Elite","Torpedo","Astromech"]},{name:"Garven Dreis",done:!0,faction:"REBEL",unique:!0,unit:"X-Wing",removefocustoken:function(){waitingforaction.add(function(){this.focus--;
this.show();var a=[],a=this.selectnearbyunits(2,function(a,c){return a.team==c.team&&a!=c});0<a.length&&(log("["+this.name+"] focus -> other friendly ship"),this.resolveactionselection(a,function(b){log(a[b].name+"  selected by Garven");a[b].addfocustoken();nextstep()}))}.bind(this))},skill:6,points:26,upgrades:["Torpedo","Astromech"]},{name:"Red Squadron Pilot",done:!0,unit:"X-Wing",faction:"REBEL",skill:4,points:23,upgrades:["Torpedo","Astromech"]},{name:"Rookie Pilot",done:!0,unit:"X-Wing",faction:"REBEL",
skill:2,points:21,upgrades:["Torpedo","Astromech"]},{name:"Biggs Darklighter",done:!0,init:function(){var a=Weapon.prototype.getrangeallunits;Weapon.prototype.getrangeallunits=function(){var b=a.call(this);log("[Biggs Darklighter] is the only target");for(i=0;i<b.length;i++){var c=b[i];if("Biggs Darklighter"==c.name)return[c]}return b}},unique:!0,unit:"X-Wing",faction:"REBEL",skill:5,points:25,upgrades:["Torpedo","Astromech"]},{name:"Luke Skywalker",done:!0,faction:"REBEL",init:function(){this.adddefensemodd(this,
function(a,b){return!0},function(a,b){return 0<Math.floor(a/10)?(log("["+this.name+"] 1 <code class='xfocustoken'></code>-> 1 <code class='xevadetoken'></code>"),a-9):a}.bind(this),!1,"focus")},unique:!0,unit:"X-Wing",skill:8,points:28,upgrades:["Elite","Torpedo","Astromech"]},{name:"Gray Squadron Pilot",done:!0,faction:"REBEL",unit:"Y-Wing",skill:4,points:20,upgrades:["Turret","Torpedo","Torpedo","Astromech"]},{name:"'Dutch' Vander",done:!0,addtarget:function(a){waitingforaction.add(function(){Unit.prototype.addtarget.call(this,
a);var b=this.selectnearbyunits(2,function(a,b){return a.team==b.team&&a!=b});0<b.length&&(b.push(this),log("<b>["+this.name+"] selects ship that may acquire target lock (self to cancel)</b>"),this.resolveactionselection(b,function(a){a<b.length-1&&(log(b[a].name+"  selected by 'Dutch' Vander"),b[a].resolvetarget())}))}.bind(this))},faction:"REBEL",unique:!0,unit:"Y-Wing",skill:6,points:23,upgrades:["Turret","Torpedo","Torpedo","Astromech"]},{name:"Horton Salm",done:!0,faction:"REBEL",unique:!0,unit:"Y-Wing",
skill:8,points:25,init:function(){unit=this;this.addattackrerolla(this,["blank"],function(){return 10},function(a,b){var c=this.getrange(b);return 2<=c&&3>=c?(log("["+this.name+"] reroll any blank result"),!0):!1}.bind(this),!1)},upgrades:["Turret","Torpedo","Torpedo","Astromech"]},{name:"Gold Squadron Pilot",done:!0,unit:"Y-Wing",faction:"REBEL",skill:2,points:18,upgrades:["Turret","Torpedo","Torpedo","Astromech"]},{name:"Academy Pilot",done:!0,unit:"TIE Fighter",faction:"EMPIRE",skill:1,points:12,
upgrades:[]},{name:"Obsidian Squadron Pilot",done:!0,unit:"TIE Fighter",faction:"EMPIRE",skill:3,points:13,upgrades:[]},{name:"Black Squadron Pilot",done:!0,unit:"TIE Fighter",faction:"EMPIRE",skill:4,points:14,upgrades:["Elite"]},{name:"'Winged Gundark'",faction:"EMPIRE",init:function(){this.addattackmoda(this,function(a,b){return 1==this.getrange(targetunit)}.bind(this),function(a,b){return 0<(a-10*Math.floor(a/10))%100?(log("["+this.name+"] 1 <code class='hit'></code> -> 1 <code class='critical'></code>"),
a+9):a}.bind(this),!1,"hit")},done:!0,unique:!0,unit:"TIE Fighter",skill:5,points:15,upgrades:[]},{name:"'Night Beast'",faction:"EMPIRE",done:!0,init:function(){var a=this.handledifficulty;this.handledifficulty=function(b){a.call(this,b);"GREEN"==b&&(log("["+this.name+"] green maneuver -> free focus action"),this.addfocus())}.bind(this)},unique:!0,unit:"TIE Fighter",skill:5,points:15,upgrades:[]},{name:"'Backstabber'",unique:!0,done:!0,faction:"EMPIRE",init:function(){var a=this.getattackstrength;
this.getattackstrength=function(b,c){var d=a.call(this,b,c);3<c.gethitsector(this)&&(d+=1,log("["+this.name+"] +1 attack against "+c.name));return d}},unit:"TIE Fighter",skill:6,points:16,upgrades:[]},{name:"'Dark Curse'",done:!0,faction:"EMPIRE",unique:!0,init:function(){var a=Unit.prototype.getattackrerolltokens,b=Unit.prototype.canusefocus,c=Unit.prototype.canusetarget,d=this;Unit.prototype.getattackrerolltokens=function(){return targetunit==d&&this.team!=d.team?"":a.call(this)};Unit.prototype.canusefocus=
function(){return targetunit==d&&this.team!=d.team?!1:b.call(this)};Unit.prototype.canusetarget=function(){return targetunit==d&&this.team!=d.team?!1:c.call(this)}},unit:"TIE Fighter",skill:6,points:16,upgrades:[]},{name:"'Mauler Mithel'",faction:"EMPIRE",done:!0,init:function(){var a=this.getattackstrength;this.getattackstrength=function(b,c){var d=a.call(this,b,c);return 1==this.gethitrange(b,c)?(log("["+this.name+"] +1 attacking "+c.name),d+1):d}.bind(this)},unique:!0,unit:"TIE Fighter",skill:7,
points:17,upgrades:["Elite"]},{name:"'Howlrunner'",unique:!0,done:!0,faction:"EMPIRE",unit:"TIE Fighter",skill:8,init:function(){this.addattackrerolla(this,["blank","focus"],function(){return 1},function(a,b,c){return!this.dead&&a!=this&&1==a.getrange(this)&&a.team==this.team&&b.isprimary?(log("["+this.name+"] 1 attack reroll for "+a.name),!0):!1}.bind(this),!0)},points:18,upgrades:["Elite"]},{name:"Maarek Stele",unique:!0,faction:"EMPIRE",unit:"TIE Advanced",skill:7,points:27,upgrades:["Elite","Missile"]},
{name:"Tempest Squadron Pilot",faction:"EMPIRE",done:!0,unit:"TIE Advanced",skill:2,points:21,upgrades:["Missile"]},{name:"Storm Squadron Pilot",faction:"EMPIRE",done:!0,unit:"TIE Advanced",skill:4,points:23,upgrades:["Missile"]},{name:"Darth Vader",faction:"EMPIRE",unique:!0,done:!0,unit:"TIE Advanced",skill:9,timeforaction:function(){1==this.nbaction&&log("["+this.name+"] 2 actions / round");return this==activeunit&&this.hasmoved&&2>this.nbaction&&phase==ACTIVATION_PHASE},endaction:function(){this.nbaction++;
this.action=-1;this.actiondone=!0;document.dispatchEvent(actionevent());return!0},endactivationphase:function(){Unit.prototype.endactivationphase.call(this);this.nbaction=0},init:function(){this.nbaction=0},points:29,upgrades:["Elite","Missile"]},{name:"Alpha Squadron Pilot",faction:"EMPIRE",done:!0,unit:"TIE Interceptor",skill:1,points:18,upgrades:[]},{name:"Avenger Squadron Pilot",faction:"EMPIRE",done:!0,unit:"TIE Interceptor",skill:3,points:20,upgrades:[]},{name:"Saber Squadron Pilot",faction:"EMPIRE",
done:!0,unit:"TIE Interceptor",skill:4,points:21,upgrades:["Elite"]},{name:"'Fel's Wrath'",faction:"EMPIRE",unique:!0,unit:"TIE Interceptor",skill:5,done:!0,endcombatphase:function(){this.hasfired=0;this.checkdead()},canbedestroyed:function(a){return-1==a?!0:!1},points:23,upgrades:[]},{name:"Turr Phennir",faction:"EMPIRE",unique:!0,done:!0,unit:"TIE Interceptor",skill:7,endattack:function(a,b){log("Adding action for Turr Phennir");waitingforaction.add(function(){console.log("["+this.name+"] free boost or roll action");
var a=this.getpathmatrix(this.m.clone().add(MR(90,0,0)).add(MT(0,this.islarge?-20:0)),"F1").add(MR(-90,0,0)).add(MT(0,-20)),b=this.getpathmatrix(this.m.clone().add(MR(-90,0,0)).add(MT(0,this.islarge?-20:0)),"F1").add(MR(90,0,0)).add(MT(0,-20));this.resolveactionmove([a,a.clone().add(MT(0,20)),a.clone().add(MT(0,40)),b.clone(),b.clone().add(MT(0,20)),b.clone().add(MT(0,40)),this.m,this.getpathmatrix(this.m.clone(),"F1"),this.getpathmatrix(this.m.clone(),"BL1"),this.getpathmatrix(this.m.clone(),"BR1")],
function(a){this.show();log("call endaction Turr Phennir");this.endaction()}.bind(this),!0,!1)}.bind(this));Unit.prototype.endattack.call(this,a,b)},points:25,upgrades:["Elite"]},{name:"Soontir Fel",faction:"EMPIRE",unique:!0,done:!0,addstress:function(){this.stress++;log("["+this.name+"] stress -> free focus action");this.addfocustoken()},unit:"TIE Interceptor",skill:9,points:27,upgrades:["Elite"]},{name:"Tycho Celchu",faction:"REBEL",unique:!0,done:!0,updateactionlist:function(){0<this.collision||
0<this.ocollision.template||-1<this.ocollision.overlap?this.actionList=["NOTHING"]:(this.actionList=this.ship.actionList.slice(0),this.actionList.push("NOTHING"))},unit:"A-Wing",skill:8,points:26,upgrades:["Elite","Missile"]},{name:"Arvel Crynyd",faction:"REBEL",unique:!0,done:!0,unit:"A-Wing",checkcollision:function(a){return!1},skill:6,points:23,upgrades:["Missile"]},{name:"Green Squadron Pilot",faction:"REBEL",done:!0,unit:"A-Wing",skill:3,points:19,upgrades:["Elite","Missile"]},{name:"Prototype Pilot",
faction:"REBEL",done:!0,unit:"A-Wing",skill:1,points:17,upgrades:["Missile"]},{name:"Outer Rim Smuggler",faction:"REBEL",unit:"YT-1300",done:!0,install:function(){this.hull=6;this.shield=4;this.fire=2},uninstall:function(){this.hull=8;this.fire=this.shield=5},skill:1,points:27,upgrades:["Crew","Crew"]},{name:"Chewbacca",unique:!0,faction:"REBEL",unit:"YT-1300",skill:5,points:42,upgrades:["Elite","Missile","Crew","Crew"]},{name:"Lando Calrissian",faction:"REBEL",unique:!0,unit:"YT-1300",skill:7,points:44,
upgrades:["Elite","Missile","Crew","Crew"],attack:3,agility:1,hull:8,shields:5},{name:"Han Solo",unique:!0,done:!0,faction:"REBEL",unit:"YT-1300",skill:9,points:46,init:function(){this.addattackrerolla(this,["blank","focus","hit","critical"],function(){return 10},function(a,b){return!0}.bind(this),!1)},upgrades:["Elite","Missile","Crew","Crew"]},{name:"Kath Scarlet",unique:!0,faction:"EMPIRE",unit:"Firespray-31",skill:7,done:!0,init:function(){var a=Unit.prototype.cancelcritical;Unit.prototype.cancelcritical=
function(b,c,d){b=a.call(this,b,c,d);0<b&&this.addstress();return b}},points:38,upgrades:["Elite","Cannon","Bomb","Crew","Missile"]},{name:"Boba Fett",unique:!0,done:!0,faction:"EMPIRE",completemaneuver:function(a,b,c){if(a.match("BL3|BL2|BL1")){var d=a.replace(/L/,"R");this.resolveactionmove([this.getpathmatrix(this.m.clone(),b),this.getpathmatrix(this.m.clone(),d)],function(e,f){0==f?Unit.prototype.completemaneuver.call(this,a,b,c):Unit.prototype.completemaneuver.call(this,d,d,c)}.bind(this),!1,
!0)}else a.match("BR3|BR2|BR1")?(d=a.replace(/R/,"L"),this.resolveactionmove([this.getpathmatrix(this.m.clone(),a),this.getpathmatrix(this.m.clone(),d)],function(e,f){0==f?Unit.prototype.completemaneuver.call(this,a,b,c):Unit.prototype.completemaneuver.call(this,a,d,c)}.bind(this),!1,!0)):Unit.prototype.completemaneuver.call(this,a,b,c)},unit:"Firespray-31",skill:8,points:39,upgrades:["Elite","Cannon","Bomb","Crew","Missile"]},{name:"Krassis Trelix",unique:!0,done:!0,faction:"EMPIRE",unit:"Firespray-31",
init:function(){this.addattackrerolla(this,["blank","focus"],function(){return 1},function(a,b){return a.isprimary?!1:(log("["+this.name+"] +1 reroll"),!0)}.bind(this),!1)},skill:5,points:36,upgrades:["Cannon","Bomb","Crew","Missile"]},{name:"Bounty Hunter",unit:"Firespray-31",skill:3,done:!0,faction:"EMPIRE",points:33,upgrades:["Cannon","Bomb","Crew","Missile"]},{name:"Ten Numb",faction:"REBEL",unique:!0,done:!0,unit:"B-Wing",skill:8,init:function(){var a=Unit.prototype.cancelcritical;Unit.prototype.cancelcritical=
function(b,c,d){c=a.call(this,b,c,d);return"Ten Numb"==activeunit.name&&1<b&&0==c?1:c}},points:31,upgrades:["Elite","System","Cannon","Torpedo","Torpedo"]},{name:"Ibtisam",unique:!0,done:!0,faction:"REBEL",unit:"B-Wing",skill:6,points:28,init:function(){this.addattackrerolla(this,["blank","focus"],function(){return 1},function(a,b){return 0<this.stress?(log("["+this.name+"] +1 attack reroll (stressed)"),!0):!1}.bind(this),!1);this.adddefensererolld(this,["blank","focus"],function(){return 1},function(a,
b){return 0<this.stress?(log("["+this.name+"] +1 defense reroll (stressed)"),!0):!1}.bind(this),!1)},upgrades:["Elite","System","Cannon","Torpedo","Torpedo"]},{name:"Dagger Squadron Pilot",unit:"B-Wing",done:!0,faction:"REBEL",skill:4,points:24,upgrades:["System","Cannon","Torpedo","Torpedo"]},{name:"Blue Squadron Pilot",unit:"B-Wing",done:!0,faction:"REBEL",skill:2,points:22,upgrades:["System","Cannon","Torpedo","Torpedo"]},{name:"Rebel Operative",unit:"HWK-290",done:!0,faction:"REBEL",skill:2,points:16,
upgrades:["Turret","Crew"]},{name:"Roark Garnet",unique:!0,faction:"REBEL",unit:"HWK-290",skill:4,begincombatphase:function(){this.dead||waitingforaction.add(function(){log("<b>["+this.name+"] select a pilot to set its skill to 12</b>");var a=selectnearbyunits(3,function(a,c){return a.team==c.team&&a!=c});0<a.length&&(this.resolveactionselection(a,function(b){a[b].oldskill=a[b].skill;a[b].skill=12;filltabskill();a[b].show();log("["+this.name+"] pilot skill of 12 for "+a[b].name);a[b].endcombatphase=
function(){this.skill=this.oldskill;squadron.sort(function(a,b){return b.skill-a.skill});this.show()}.bind(a[b])}.bind(this)),nextstep())}.bind(this))},done:!0,points:19,upgrades:["Turret","Crew"]},{name:"Kyle Katarn",faction:"REBEL",unique:!0,done:!0,unit:"HWK-290",skill:6,points:21,begincombatphase:function(){0<this.focus&&waitingforaction.add(function(){var a=selectnearbyunits(3,function(a,c){return c.team==a.team&&c!=a});0<a.length?(a.push(this),log("<b>["+this.name+"] assigns one focus token to a friendly unit (self to cancel)</b>"),
this.resolveactionselection(a,function(b){this!=a[b]&&(this.removefocustoken(),a[b].addfocustoken(),log("["+this.name+"] focus token assigned to "+a[b].name));nextstep()}.bind(this))):nextstep()}.bind(this))},upgrades:["Elite","Turret","Crew"]},{name:"Jan Ors",faction:"REBEL",unique:!0,done:!0,unit:"HWK-290",skill:8,init:function(){var a=this;this.addattackmoda(this,function(b,c){return 0==a.stress&&activeunit.team==a.team&&activeunit!=a&&3>=a.getrange(activeunit)}.bind(this),function(b,c){var d=
Math.floor(7*Math.random()),d=FACE[ATTACKDICE[d]];a.addstress();log("["+a.name+"] +1 attack die");return"focus"==d?b+100:"hit"==d?b+1:"critical"==d?b+10:b}.bind(this),!0,"hit")},points:25,upgrades:["Elite","Turret","Crew"]},{name:"Scimitar Squadron Pilot",done:!0,unit:"TIE Bomber",skill:2,faction:"EMPIRE",points:16,upgrades:["Torpedo","Torpedo","Missile","Missile","Bomb"]},{name:"Gamma Squadron Pilot",done:!0,unit:"TIE Bomber",faction:"EMPIRE",skill:4,points:18,upgrades:["Torpedo","Torpedo","Missile",
"Missile","Bomb"]},{name:"Captain Jonus",faction:"EMPIRE",done:!0,init:function(){this.addattackrerolla(this,["blank","focus"],function(){return 2},function(a,b,c){return this.dead||a==this||1!=a.getrange(this)||a.team!=this.team||1==b.isprimary?!1:(log("["+this.name+"] 2 reroll for "+a.name),!0)}.bind(this),!0)},unique:!0,unit:"TIE Bomber",skill:6,points:22,upgrades:"Elite Torpedo Torpedo Missile Missile Bomb".split(" ")},{name:"Major Rhymer",done:!0,faction:"EMPIRE",init:function(){for(var a=0;a<
this.weapons.length;a++){var b=this.weapons[a].range[1];1<this.weapons[a].range[0]&&this.weapons[a].range[0]--;3>b&&this.weapons[a].range[1]++}log("["+this.name+"] extending weapon ranges")},unique:!0,unit:"TIE Bomber",skill:7,points:26,upgrades:"Elite Torpedo Torpedo Missile Missile Bomb".split(" ")},{name:"Captain Kagi",faction:"EMPIRE",unique:!0,done:!0,init:function(){var a=Unit.prototype.gettargetableunits;Unit.prototype.gettargetableunits=function(b){b=a.call(this,b);for(var c=0;c<b.length;c++)if("Captain Kagi"==
b[c].name)return[b[c]];return b}},unit:"Lambda-Class Shuttle",skill:8,points:27,upgrades:["System","Cannon","Crew","Crew"]},{name:"Colonel Jendon",faction:"EMPIRE",begincombatphase:function(){this.dead||waitingforaction.add(function(){var a=selectnearbyunits(1,function(a,c){return a.team==c.team&&0==a.targeting.length&&a!=c});0<a.length?(a.push(this),log("["+this.name+"] assigns target lock to a friendly unit (self to cancel)"),this.resolveactionselection(a,function(b){if(this!=a[b]){var c=this.targeting[0];
a[b].addtarget(c);this.removetarget(c);log("["+this.name+"] "+a[b].name+" targets "+c.name)}nextstep()}.bind(this))):nextstep()}.bind(this))},done:!0,unique:!0,unit:"Lambda-Class Shuttle",skill:6,points:26,upgrades:["System","Cannon","Crew","Crew"]},{name:"Captain Yorr",faction:"EMPIRE",unique:!0,done:!0,unit:"Lambda-Class Shuttle",skill:4,init:function(){var a=this;Unit.prototype.addstress=function(){2>=this.getrange(a)&&2>=a.stress&&a.addstress()}},points:24,upgrades:["System","Cannon","Crew","Crew"]},
{name:"Omicron Group Pilot",faction:"EMPIRE",done:!0,unit:"Lambda-Class Shuttle",skill:2,points:21,upgrades:["System","Cannon","Crew","Crew"]},{name:"Lieutenant Lorrir",faction:"EMPIRE",unique:!0,done:!0,unit:"TIE Interceptor",skill:5,points:23,resolveroll:function(){var a=this.getpathmatrix(this.m.clone().add(MR(90,0,0)).add(MT(0,this.islarge?-20:0)),"F1").add(MR(-90,0,0)).add(MT(0,-20)),b=this.getpathmatrix(this.m.clone().add(MR(-90,0,0)).add(MT(0,this.islarge?-20:0)),"F1").add(MR(90,0,0)).add(MT(0,
-20)),c=this.getpathmatrix(this.m.clone().add(MR(90,0,0)).add(MT(0,this.islarge?-20:0)),"BR1").add(MR(-90,0,0)).add(MT(0,-20)),d=this.getpathmatrix(this.m.clone().add(MR(-90,0,0)).add(MT(0,this.islarge?-20:0)),"BR1").add(MR(90,0,0)).add(MT(0,-20)),e=this.getpathmatrix(this.m.clone().add(MR(90,0,0)).add(MT(0,this.islarge?-20:0)),"BL1").add(MR(-90,0,0)).add(MT(0,-20)),f=this.getpathmatrix(this.m.clone().add(MR(-90,0,0)).add(MT(0,this.islarge?-20:0)),"BL1").add(MR(90,0,0)).add(MT(0,-20));this.resolveactionmove([a.clone().add(MT(0,
0)),a.clone().add(MT(0,20)),a.clone().add(MT(0,40)),b.clone().add(MT(0,0)),b.clone().add(MT(0,20)),b.clone().add(MT(0,40)),c.clone().add(MT(0,0)),c.clone().add(MT(0,20)),c.clone().add(MT(0,40)),d.clone().add(MT(0,0)),d.clone().add(MT(0,20)),d.clone().add(MT(0,40)),e.clone().add(MT(0,0)),e.clone().add(MT(0,20)),e.clone().add(MT(0,40)),f.clone().add(MT(0,0)),f.clone().add(MT(0,20)),f.clone().add(MT(0,40))],function(a,b){5<b&&a.addstress();a.endaction()},!0);return!0},upgrades:[]},{name:"Royal Guard Pilot",
faction:"EMPIRE",done:!0,unit:"TIE Interceptor",skill:6,points:22,upgrades:["Elite"]},{name:"Tetran Cowall",faction:"EMPIRE",unique:!0,done:!0,completemaneuver:function(a,b,c){a.match("K5|K3")?this.resolveactionmove([this.getpathmatrix(this.m.clone(),"K1"),this.getpathmatrix(this.m.clone(),"K3"),this.getpathmatrix(this.m.clone(),"K5")],function(b,e){var f="K5";0==e&&(f="K1");1==e&&(f="K3");Unit.prototype.completemaneuver.call(b,a,f,c)},!1,!0):Unit.prototype.completemaneuver.call(this,a,b,c)},unit:"TIE Interceptor",
skill:7,points:24,upgrades:["Elite"]},{name:"Kir Kanos",faction:"EMPIRE",useevade:function(){var a=Unit.prototype.useevade,b=this.getrange(targetunit);a.call(this);phase==COMBAT_PHASE&&this.canuseevade()&&this==activeunit&&3>=b&&2<=b&&(this.removeevadetoken(),$("atokens .xevadetoken").remove(),$("#attack").append("<b class='hitreddice'></b>"),log("["+this.name+"] +1 <code class='hit'></code> for attacking at range 2-3"))},done:!0,unique:!0,unit:"TIE Interceptor",skill:6,points:24,upgrades:[]},{name:"Carnor Jax",
faction:"EMPIRE",init:function(){var a=Unit.prototype.canusefocus,b=Unit.prototype.canuseevade,c=Unit.prototype.candofocus,d=Unit.prototype.candoevade,e=this;Unit.prototype.canusefocus=function(){return 1==this.getrange(e)&&this.team!=e.team?!1:a.call(this)};Unit.prototype.canuseevade=function(){return 1==this.getrange(e)&&this.team!=e.team?!1:b.call(this)};Unit.prototype.candofocus=function(){return 1==this.getrange(e)&&this.team!=e.team?!1:c.call(this)};Unit.prototype.candoevade=function(){return 1==
this.getrange(e)&&this.team!=e.team?!1:d.call(this)}},unique:!0,done:!0,unit:"TIE Interceptor",skill:8,points:26,upgrades:["Elite"]},{name:"Bandit Squadron Pilot",faction:"REBEL",done:!0,unit:"Z-95 Headhunter",skill:2,points:12,upgrades:["Missile"]},{name:"Tala Squadron Pilot",faction:"REBEL",done:!0,unit:"Z-95 Headhunter",skill:4,points:13,upgrades:["Missile"]},{name:"Lieutenant Blount",faction:"REBEL",done:!0,endattack:function(a,b){0==a+b&&(log("["+this.name+"] target is hit"),targetunit.ishit(this));
Unit.prototype.endattack.call(this,a,b)},unique:!0,unit:"Z-95 Headhunter",skill:6,points:17,upgrades:["Elite","Missile"]},{name:"Airen Cracken",faction:"REBEL",done:!0,endattack:function(){waitingforaction.add(function(){var a=this.selectnearbyunits(1,function(a,c){return a.team==c.team&&c!=a});0<a.length?(log("<b>["+this.name+"] assigns a free action to friendly unit"),this.resolveactionselection(a,function(b){a[b].freeaction(function(){nextstep()})})):nextstep()}.bind(this))},unique:!0,unit:"Z-95 Headhunter",
skill:8,points:19,upgrades:["Elite","Missile"]},{name:"Delta Squadron Pilot",faction:"EMPIRE",done:!0,unit:"TIE Defender",skill:1,points:30,upgrades:["Cannon","Missile"]},{name:"Onyx Squadron Pilot",done:!0,faction:"EMPIRE",unit:"TIE Defender",skill:3,points:32,upgrades:["Cannon","Missile"]},{name:"Colonel Vessery",done:!0,faction:"EMPIRE",attackroll:function(a){a=Unit.prototype.ar.call(this);targetunit.istargeted&&0==this.target&&(this.addtarget(targetunit),log("["+this.name+"] lock target "+targetunit.name));
return a},unique:!0,unit:"TIE Defender",skill:6,points:35,upgrades:["Elite","Cannon","Missile"]},{name:"Rexler Brath",faction:"EMPIRE",unique:!0,unit:"TIE Defender",skill:8,points:37,upgrades:["Elite","Cannon","Missile"]},{name:"Knave Squadron Pilot",faction:"REBEL",done:!0,unit:"E-Wing",skill:1,points:27,upgrades:["System","Torpedo","Astromech"]},{name:"Blackmoon Squadron Pilot",faction:"REBEL",done:!0,unit:"E-Wing",skill:3,points:29,upgrades:["System","Torpedo","Astromech"]},{name:"Etahn A'baht",
done:!0,faction:"REBEL",init:function(){var a=this;this.addattackmoda(this,function(b,c){return targetunit.team!=a.team&&a.isinsector(a.m,3,targetunit)}.bind(this),function(b,c){return 0<(b-10*Math.floor(b/10))%100?(log("["+a.name+"] 1 <code class='hit'></code>-> 1 <code class='critical'></code>"),b+9):b}.bind(this),!0,"hit")},unique:!0,unit:"E-Wing",skill:5,points:32,upgrades:["Elite","System","Torpedo","Astromech"]},{name:"Corran Horn",faction:"REBEL",done:!0,endcombatphase:function(){"undefined"==
typeof this.hasdoubledfired&&(this.hasdoubledfired=0);if(0==this.hasdoubledfired){Unit.prototype.endcombatphase.call(this);var a=activeunit,b=this.skill;activeunit=this;this.hasfired=0;this.hasdoubledfired=round;this.skill=-1;this.select();a.unselect();log("["+this.name+"] New attack possible (no attack next turn)");this.showattack();this.skill=b;this.showstats()}this.hasdoubledfired==round-1&&(this.hasdoubledfired=this.hasfired=0,log("["+this.name+"] can fire next turn."))},unique:!0,unit:"E-Wing",
skill:8,points:35,upgrades:["Elite","System","Torpedo","Astromech"]},{name:"Sigma Squadron Pilot",faction:"EMPIRE",done:!0,unit:"TIE Phantom",skill:3,points:25,upgrades:["System","Crew"]},{name:"Shadow Squadron Pilot",done:!0,faction:"EMPIRE",unit:"TIE Phantom",skill:5,points:27,upgrades:["System","Crew"]},{name:"'Echo'",faction:"EMPIRE",done:!0,resolveuncloak:function(){waitingforaction.add(function(){var a=this.getpathmatrix(this.m.clone().add(MR(90,0,0)).add(MT(0,this.islarge?-20:0)),"F2").add(MR(-90,
0,0)).add(MT(0,-20)),b=this.getpathmatrix(this.m.clone().add(MR(-90,0,0)).add(MT(0,this.islarge?-20:0)),"F2").add(MR(90,0,0)).add(MT(0,20)),c=this.getpathmatrix(this.m.clone().add(MR(90,0,0)).add(MT(0,this.islarge?-20:0)),"BL2").add(MR(-90,0,0)).add(MT(0,-20)),d=this.getpathmatrix(this.m.clone().add(MR(-90,0,0)).add(MT(0,this.islarge?-20:0)),"BL2").add(MR(90,0,0)).add(MT(0,20)),e=this.getpathmatrix(this.m.clone().add(MR(90,0,0)).add(MT(0,this.islarge?-20:0)),"BR2").add(MR(-90,0,0)).add(MT(0,-20)),
f=this.getpathmatrix(this.m.clone().add(MR(-90,0,0)).add(MT(0,this.islarge?-20:0)),"BR2").add(MR(90,0,0)).add(MT(0,20)),g=this.getpathmatrix(this.m.clone(),"F2");this.resolveactionmove([a.clone().add(MT(0,0)),a.clone().add(MT(0,20)),a.clone().add(MT(0,40)),g,b.clone().add(MT(0,0)),b.clone().add(MT(0,-20)),b.clone().add(MT(0,-40)),c.clone().add(MT(0,0)),c.clone().add(MT(0,20)),c.clone().add(MT(0,40)),d.clone().add(MT(0,0)),d.clone().add(MT(0,20)),d.clone().add(MT(0,40)),e.clone().add(MT(0,0)),e.clone().add(MT(0,
20)),e.clone().add(MT(0,40)),f.clone().add(MT(0,0)),f.clone().add(MT(0,20)),f.clone().add(MT(0,40))],function(a,b){a.agility-=2;a.iscloaked=!1;a.show();SOUNDS.uncloak.play();nextstep()},!0)}.bind(this));return!0},unique:!0,unit:"TIE Phantom",skill:6,points:30,upgrades:["Elite","System","Crew"]},{name:"'Whisper'",faction:"EMPIRE",done:!0,resolvedamage:function(){var a=targetunit.evadeattack(this);Unit.prototype.resolvedamage.call(this);0<a.c+a.h&&(log("["+this.name+"] +1 focus token when hitting "+
targetunit.name),this.addfocustoken())},unique:!0,unit:"TIE Phantom",skill:7,points:32,upgrades:["Elite","System","Crew"]},{name:"Wes Janson",done:!0,endattack:function(a,b){Unit.prototype.endattack.call(this,a,b);0<targetunit.target+targetunit.focus+targetunit.evade&&log("["+this.name+"] removing token from "+targetunit.name);0<targetunit.targeting.length?targetunit.removetarget(targetunit.targeting[0]):0<targetunit.focus?targetunit.removefocustoken():0<targetunit.evade&&targetunit.removeevadetoken();
Unit.prototype.endcombatphase.call(this)},faction:"REBEL",unique:!0,unit:"X-Wing",skill:8,points:29,upgrades:["Elite","Torpedo","Astromech"]},{name:"Jek Porkins",done:!0,addstress:function(){var a=Math.floor(7*Math.random()),a=FACE[ATTACKDICE[a]];log("["+this.name+"] remove 1 stress token, roll 1 attack dice");"hit"==a&&(this.resolvehit(1),this.checkdead())},faction:"REBEL",unique:!0,unit:"X-Wing",skill:7,points:26,upgrades:["Elite","Torpedo","Astromech"]},{name:"'Hobbie' Klivian",faction:"REBEL",
done:!0,removetarget:function(a){this.stress&&(log("["+this.name+"] using target -> removes a stress token"),this.removestresstoken());Unit.prototype.removetarget.call(this,a)},addtarget:function(a){this.stress&&(this.removestresstoken(),log("["+this.name+"] targeting -> removes a stress token"));Unit.prototype.addtarget.call(this,a)},unique:!0,unit:"X-Wing",skill:5,points:25,upgrades:["Torpedo","Astromech"]},{name:"Tarn Mison",done:!0,isattackedby:function(a,b){if(0==this.target||this.skill<b.skill)log("["+
this.name+"] free target token on "+b.name),this.addtarget(b)},faction:"REBEL",unique:!0,unit:"X-Wing",skill:3,points:23,upgrades:["Torpedo","Astromech"]},{name:"Jake Farrell",faction:"REBEL",done:!0,freemove:function(){waitingforaction.add(function(){log("["+this.name+"] free boost or roll action");var a=this.getpathmatrix(this.m.clone().add(MR(90,0,0)).add(MT(0,this.islarge?-20:0)),"F1").add(MR(-90,0,0)).add(MT(0,-20)),b=this.getpathmatrix(this.m.clone().add(MR(-90,0,0)).add(MT(0,this.islarge?-20:
0)),"F1").add(MR(90,0,0)).add(MT(0,-20));this.resolveactionmove([a.clone().add(MT(0,0)),a.clone().add(MT(0,20)),a.clone().add(MT(0,40)),b.clone().add(MT(0,0)),b.clone().add(MT(0,20)),b.clone().add(MT(0,40)),this.m,this.getpathmatrix(this.m.clone(),"F1"),this.getpathmatrix(this.m.clone(),"BL1"),this.getpathmatrix(this.m.clone(),"BR1")],function(a){nextstep()},!0)}.bind(this))},addfocustoken:function(){this.freemove();Unit.prototype.addfocustoken.call(this)},removefocustoken:function(){this.freemove();
Unit.prototype.removefocustoken.call(this)},unique:!0,unit:"A-Wing",skill:7,points:24,upgrades:["Elite","Missile"]},{name:"Gemmer Sojan",done:!0,getdefensestrength:function(a,b){var c=Unit.prototype.getdefensestrength.call(this,a,b),d=this.getrangeallunits(),e;for(e=0;e<d[1].length;e++)if(squadron[d[1][e].unit].team!=this.team)return log("["+this.name+"] +1 defense due to ennemy at range 1"),c+1;return c},faction:"REBEL",unique:!0,unit:"A-Wing",skill:5,points:22,upgrades:["Missile"]},{name:"Keyan Farlander",
faction:"REBEL",done:!0,usestress:function(){if(phase==COMBAT_PHASE&&0<this.hasfired&&this==activeunit&&this==activeunit&&0<this.stress){this.removestresstoken();var a=$(".focusreddice").length;$(".focusreddice").remove();for(i=0;i<a;i++)$("#attack").append("<b class='hitreddice'></b>");log("["+this.name+"] focus -> hit due to stress");$("#atokens .xstresstoken").remove()}},unique:!0,unit:"B-Wing",skill:7,points:29,upgrades:["Elite","System","Cannon","Torpedo","Torpedo"]},{name:"Nera Dantels",faction:"REBEL",
done:!0,isTurret:function(a){return"Torpedo"==a.type?(log("["+this.name+"] can fire torpedos at 360 degrees"),!0):!1},unique:!0,unit:"B-Wing",skill:5,points:26,upgrades:["Elite","System","Cannon","Torpedo","Torpedo"]},{name:"Wild Space Fringer",done:!0,faction:"REBEL",unit:"YT-2400",skill:2,points:30,upgrades:["Cannon","Missile","Crew"]},{name:"Eaden Vrill",done:!0,init:function(){var a=this.getattackstrength;this.getattackstrength=function(b,c){var d=a.call(this,b,c);return 0<c.stress&&this.weapons[b].isprimary?
(log("["+this.name+"] +1 attacking "+c.name),d+1):d}.bind(this)},faction:"REBEL",unit:"YT-2400",unique:!0,skill:3,points:32,upgrades:["Cannon","Missile","Crew"]},{name:"'Leebo'",faction:"REBEL",unit:"YT-2400",unique:!0,skill:5,points:34,upgrades:["Elite","Cannon","Missile","Crew"]},{name:"Dash Rendar",faction:"REBEL",unit:"YT-2400",unique:!0,skill:7,done:!0,isintersecting:function(a,b){return 1==a.obstacle&&phase==ACTIVATION_PHASE?(log("["+this.name+"] ignores obstacles"),!1):Unit.prototype.isintersecting.call(this,
a,b)},points:36,upgrades:["Elite","Cannon","Missile","Crew"]},{name:"Patrol Leader",faction:"EMPIRE",done:!0,unit:"VT-49 Decimator",skill:3,points:40,upgrades:["Torpedo","Crew","Crew","Crew","Bomb"]},{name:"Captain Oicunn",faction:"EMPIRE",unit:"VT-49 Decimator",skill:4,points:42,unique:!0,upgrades:"Elite Torpedo Crew Crew Crew Bomb".split(" ")},{name:"Commander Kenkirk",faction:"EMPIRE",getagility:function(){return 0==this.shield&&this.hull<this.ship.hull?this.agility+1:this.agility},done:!0,unit:"VT-49 Decimator",
skill:6,points:44,unique:!0,upgrades:"Elite Torpedo Crew Crew Crew Bomb".split(" ")},{name:"Rear Admiral Chiraneau",init:function(){this.addattackmoda(this,function(a,b){return 2>=this.getrange(targetunit)}.bind(this),function(a,b){return 0<(a-10*Math.floor(a/10))%100?(log("["+this.name+"] 1 <code class='hit'></code> -> 1 <code class='critical'></code>"),a+9):a}.bind(this),!1,"hit")},faction:"EMPIRE",unit:"VT-49 Decimator",skill:8,points:46,done:!0,unique:!0,upgrades:"Elite Torpedo Crew Crew Crew Bomb".split(" ")},
{name:"Prince Xizor",faction:"SCUM",modifydamageassigned:function(a,b){var c=[];if(0==a)return 0;c=this.selectnearbyunits(1,function(a,b){return a.team==b.team&&a!=b});if(0<c.length){c.sort(function(a,b){hpa=a.hull+a.shield;hpb=b.hull+b.shield;return hpa<hpb?1:hpa>hpb?-1:0});if(10<=a)return c[0].resolvecritical(1),log("["+this.name+"] transferred 1 critical to "+c[0].name),a-10;c[0].resolvehit(1);c[0].checkdead();log("["+this.name+"] transferred 1 hit to "+c[0].name);return a-1}return a},unique:!0,
done:!0,unit:"StarViper",skill:7,points:31,upgrades:["Elite","Torpedo"]},{name:"Guri",faction:"SCUM",init:function(){var a=this.begincombatphase;this.begincombatphase=function(){a.call(this);!this.dead&&0<this.gettargetableunits(1).length&&(log("["+this.name+"] +1 focus, ennemy at range 1"),this.addfocustoken())}},done:!0,unique:!0,unit:"StarViper",skill:5,points:30,upgrades:["Elite","Torpedo"]},{name:"Black Sun Vigo",faction:"SCUM",done:!0,unit:"StarViper",skill:3,points:27,upgrades:["Torpedo"]},
{name:"Black Sun Enforcer",faction:"SCUM",done:!0,unit:"StarViper",skill:1,points:25,upgrades:["Torpedo"]},{name:"Serissu",faction:"SCUM",done:!0,init:function(){this.adddefensererolld(this,["blank","focus"],function(){return 1},function(a,b,c){return this.dead?!1:c!=this&&1==c.getrange(this)&&c.team==this.team?(log("["+this.name+"] 1 reroll for "+c.name),!0):!1}.bind(this),!0)},unit:"M3-A Interceptor",skill:8,points:20,unique:!0,upgrades:["Elite"]},{name:"Laetin A'shera",faction:"SCUM",endbeingattacked:function(a,
b){Unit.prototype.endbeingattacked.call(this,a,b);0<a+b&&this.addevade()},done:!0,unit:"M3-A Interceptor",skill:6,points:18,unique:!0,upgrades:[]},{name:"Tansarii Point Veteran",faction:"SCUM",done:!0,unit:"M3-A Interceptor",skill:5,points:17,upgrades:["Elite"]},{name:"Cartel Spacer",faction:"SCUM",done:!0,unit:"M3-A Interceptor",skill:2,points:14,upgrades:[]},{name:"IG-88A",faction:"SCUM",unique:!0,unit:"Aggressor",skill:6,points:36,endattack:function(a,b){Unit.prototype.endattack.call(this,a,b);
0>=targetunit.hull&&this.shield<unitlist[this.ship.name]&&this.shield++},done:!0,upgrades:"Elite System Cannon Cannon Bomb Illicit".split(" ")},{name:"IG-88B",faction:"SCUM",unique:!0,unit:"Aggressor",skill:6,points:36,upgrades:"Elite System Cannon Cannon Bomb Illicit".split(" ")},{name:"IG-88C",faction:"SCUM",resolveboost:function(){Unit.prototype.resolveboost.call(this);this.addevade()},done:!0,unique:!0,unit:"Aggressor",skill:6,points:36,upgrades:"Elite System Cannon Cannon Bomb Illicit".split(" ")},
{name:"IG-88D",faction:"SCUM",completemaneuver:function(a,b,c){"SL3"==a?this.resolveactionmove([this.getpathmatrix(this.m.clone(),"SL3"),this.getpathmatrix(this.m.clone(),"TL3")],function(d,e){0==e?Unit.prototype.completemaneuver.call(this,a,b,c):Unit.prototype.completemaneuver.call(this,a,"TL3",c)}.bind(this),!1,!0):"SR3"==a?this.resolveactionmove([this.getpathmatrix(this.m.clone(),"SR3"),this.getpathmatrix(this.m.clone(),"TR3")],function(b,e){0==e?Unit.prototype.completemaneuver.call(this,a,realpath,
c):Unit.prototype.completemaneuver.call(this,a,"TR3",c)}.bind(this),!1,!0):Unit.prototype.completemaneuver.call(this,a,b,c)},unique:!0,done:!0,unit:"Aggressor",skill:6,points:36,upgrades:"Elite System Cannon Cannon Bomb Illicit".split(" ")},{name:"N'Dru Suhlak",unique:!0,done:!0,faction:"SCUM",init:function(){var a=this.getattackstrength;this.getattackstrength=function(b,c){var d=a.call(this,b,c);this.getrangeallunits();for(var e=0;e<squadron.length;e++)if(2>=squadron[e].getrange(this)&&squadron[e].team==
this.team)return d;log("["+this.name+"] +1 attacking "+c.name+" at range >=3 of friendly ships");return d+1}.bind(this)},unit:"Z-95 Headhunter",skill:7,points:17,upgrades:["Elite","Missile","Illicit"]},{name:"Kaa'To Leeachos",unique:!0,faction:"SCUM",done:!0,begincombatphase:function(){this.dead||waitingforaction.add(function(){var a=this.selectnearbyunits(2,function(a,c){return a.team==c.team&&a!=c&&a.canuseevade()});0<a.length&&(a.push(this),log("["+this.name+"] select a focus/evade token to take"),
this.resolveactionselection(a,function(b){this!=a[b]&&(0<a[b].evade?(a[b].removeevadetoken(),this.addevade(),log("["+this.name+"] evade taken from "+a[b].name)):0<a[b].focus&&(a[b].removefocustoken(),this.addfocustoken(),log("["+this.name+"] focus taken from "+a[b].name)));nextstep()}.bind(this)))}.bind(this))},unit:"Z-95 Headhunter",skill:5,points:15,upgrades:["Elite","Missile","Illicit"]},{name:"Black Sun Soldier",faction:"SCUM",done:!0,unit:"Z-95 Headhunter",skill:3,points:13,upgrades:["Missile",
"Illicit"]},{name:"Binayre Pirate",faction:"SCUM",done:!0,unit:"Z-95 Headhunter",skill:1,points:12,upgrades:["Missile","Illicit"]},{name:"Boba Fett",faction:"SCUM",unit:"Firespray-31",skill:8,points:39,init:function(){var a=function(){for(var a=0,c=0;c<squadron.length;c++){var d=squadron[c];1==this.getrange(d)&&this.team!=d.team&&a++}return a}.bind(this);this.addattackrerolla(this,["blank","focus"],a,function(a,c){return!0},!1);this.adddefensererolld(this,["blank","focus"],a,function(a,c){return!0},
!1)},done:!0,unique:!0,upgrades:"Elite Cannon Bomb Crew Missile Illicit".split(" ")},{name:"Kath Scarlet",done:!0,init:function(){var a=this.getattackstrength;this.getattackstrength=function(b,c){var d=a.call(this,b,c),e=this.m.clone();this.m.add(MR(180,0,0));3>=this.gethitsector(c)&&(log("["+this.name+"] +1 attacking "+c.name+" in auxiliary arc"),d+=1);this.m=e;return d}.bind(this)},unique:!0,faction:"SCUM",unit:"Firespray-31",skill:7,points:38,upgrades:"Elite Cannon Bomb Crew Missile Illicit".split(" ")},
{name:"Emon Azzameen",done:!0,unique:!0,init:function(){var a=Bomb.prototype.drop,b=this;Bomb.prototype.drop=function(c){this.unit==b?waitingforaction.add(function(){this.resolveactionmove([b.getpathmatrix(b.m.clone().add(MR(180,0,0)),"BL3"),b.getpathmatrix(b.m.clone().add(MR(180,0,0)),"BR3"),b.getpathmatrix(b.m.clone().add(MR(180,0,0)),"F3")],function(b){a.call(this,this.m);nextstep()}.bind(this))}.bind(this)):a.call(this,c)}},faction:"SCUM",unit:"Firespray-31",skill:6,points:36,upgrades:["Cannon",
"Bomb","Crew","Missile","Illicit"]},{name:"Mandalorian Mercenary",faction:"SCUM",done:!0,unit:"Firespray-31",skill:5,points:35,upgrades:"Elite Cannon Bomb Crew Missile Illicit".split(" ")},{name:"Kavil",unique:!0,done:!0,init:function(){var a=this.getattackstrength;this.getattackstrength=function(b,c){var d=a.call(this,b,c);return 3<this.gethitsector(c)?(log("["+this.name+"] +1 attacking "+c.name+" outside firing arc"),d+1):d}.bind(this)},faction:"SCUM",unit:"Y-Wing",skill:7,points:24,upgrades:["Elite",
"Turret","Torpedo","Torpedo","Salvaged"]},{name:"Drea Renthal",unique:!0,faction:"SCUM",unit:"Y-Wing",skill:5,done:!0,removetarget:function(a){waitingforaction.add(function(){Unit.prototype.removetarget.call(this,a);var b=this.gettargetableunits(3);b.push(this);log("<b>["+this.name+"] selects new target to lock at the cost of 1 stress (self to cancel)</b>");this.resolveactionselection(b,function(a){a<b.length-1&&(this.addtarget(b[a]),this.addstress());nextstep()}.bind(this))}.bind(this))},points:22,
upgrades:["Turret","Torpedo","Torpedo","Salvaged"]},{name:"Hired Gun",faction:"SCUM",done:!0,unit:"Y-Wing",skill:4,points:20,upgrades:["Turret","Torpedo","Torpedo","Salvaged"]},{name:"Syndicate Thug",faction:"SCUM",done:!0,unit:"Y-Wing",skill:2,points:18,upgrades:["Turret","Torpedo","Torpedo","Salvaged"]},{name:"Dace Bonearm",unique:!0,faction:"SCUM",unit:"HWK-290",done:!0,init:function(){var a=this,b=Unit.prototype.addiontoken;Unit.prototype.addiontoken=function(){b.call(this);0==a.stress&&3>=this.getrange(a)&&
this.faction!=a.faction&&(a.addstress(),this.resolvehit(1),log("["+a.name+"] +1 stress for 1<code class='hit'></code> to "+this.name),this.checkdead())}},skill:7,points:23,upgrades:["Elite","Turret","Crew","Illicit"]},{name:"Palob Godalhi",unique:!0,faction:"SCUM",unit:"HWK-290",begincombatphase:function(){this.dead||waitingforaction.add(function(){var a=this.selectnearbyunits(2,function(a,c){return a.team!=c.team&&(a.canusefocus()||a.canuseevade())});0<a.length&&(a.push(this),log("["+this.name+"] selects enemy ship to remove focus/evade token (self to cancel)"),
this.resolveactionselection(a,function(b){this!=a[b]&&(0<a[b].evade?(a[b].removeevadetoken(),this.addevade(),log("["+this.name+"] evade taken from "+a[b].name)):0<a[b].focus&&(a[b].removefocustoken(),this.addfocustoken(),log("["+this.name+"] focus taken from "+a[b].name)));nextstep()}.bind(this)))}.bind(this))},done:!0,skill:5,points:20,upgrades:["Elite","Turret","Crew","Illicit"]},{name:"Torkil Mux",unique:!0,done:!0,endactivationphase:function(){this.dead||waitingforaction.add(function(){var a=
this.gettargetableunits(2);0<a.length&&(log("<b>["+this.name+"] select a pilot to set its skill to 0.</b>"),this.resolveactionselection(a,function(b){if(this!=a[b]){var c=a[b].ecp;a[b].oldskill=a[b].skill;a[b].skill=0;filltabskill();a[b].show();log("["+this.name+"] pilot skill 0 for "+a[b].name);a[b].endcombatphase=function(){this.skill=this.oldskill;squadron.sort(function(a,b){return b.skill-a.skill});this.show();c.call(this);nextstep()}}nextstep()}.bind(this)))}.bind(this))},faction:"SCUM",unit:"HWK-290",
skill:3,points:19,upgrades:["Turret","Crew","Illicit"]},{name:"Spice Runner",faction:"SCUM",done:!0,unit:"HWK-290",skill:1,points:16,upgrades:["Turret","Crew","Illicit"]},{name:"Commander Alozen",faction:"EMPIRE",unit:"TIE Advanced",unique:!0,done:!0,skill:5,points:25,begincombatphase:function(){waitingforaction.add(function(){var a=this.gettargetableunits(1);0<a.length&&(a.push(this),log("<b>["+this.name+"] selects target to lock</b>"),this.resolveactionselection(a,function(b){this!=a[b]&&(this.addtarget(a[b]),
log("["+this.name+"] lock target "+a[b].name));nextstep()}.bind(this)))}.bind(this))},upgrades:["Elite","Missile"]}];
