var s,GREEN="#0F0",RED="#F00",WHITE="#FFF",BLUE="#0AF",YELLOW="#FF0",HALFGREEN="#080",HALFRED="#800",HALFWHITE="#888",HALFBLUE="#058",HALFYELLOW="#880",TIMEANIM=1E3,FACE=["focus","hit","critical","evade","blank"],ATTACKDICE=[0,0,1,1,1,2,4,4],DEFENSEDICE=[0,0,3,3,3,4,4,4],MPOS={F0:[0,2],F1:[1,2],F2:[2,2],F3:[3,2],F4:[4,2],F5:[5,2],BL1:[1,1],BL2:[2,1],BL3:[3,1],TL1:[1,0],TL2:[2,0],TL3:[3,0],BR1:[1,3],BR2:[2,3],BR3:[3,3],TR1:[1,4],TR2:[2,4],TR3:[3,4],K1:[1,5],K2:[2,5],K3:[3,5],K4:[4,4],K5:[5,4],SL3:[3,
0],SR3:[3,4]},generics=[],gid=0,UNIQUE=[[],[],[]],ATTACKREROLLA=[],DEFENSEREROLLD=[],ATTACKMODA=[],DEFENSEMODD=[],xws_lookup=function(a){for(var b in PILOT_dict)if(PILOT_dict[b]==a)return b;return""},upg_lookup=function(a){for(var b in UPGRADE_dict)if(UPGRADE_dict[b]==a)return b;return""},activeunit,unitlist,pilotlist,squadron=[],active=0,globalid=1,targetunit,PATTERN,SOUND_FILES="ogg/EXPLODE3 ogg/KX9_laser_cannon ogg/TIE-Fire ogg/Slave1-Guns ogg/Falcon-Guns ogg/XWing-Fly1 ogg/TIE-Fly2 ogg/Slave1-Fly1 ogg/Falcon-Fly1 ogg/Falcon-Fly3 ogg/YWing-Fly2 ogg/ISD-Fly ogg/Missile".split(" "),
SOUNDS={},SOUND_NAMES="explode xwing_fire tie_fire slave_fire falcon_fire xwing_fly tie_fly slave_fly falcon_fly yt2400_fly ywing_fly isd_fly missile".split(" ");function loadsound(){var a;for(a=0;a<SOUND_FILES.length;a++)SOUNDS[SOUND_NAMES[a]]=new buzz.sound(SOUND_FILES[a],{formats:["ogg","wav"]});SOUNDS.cloak=new buzz.sound("ogg/cloak_romulan",{formats:["ogg","mp3"]});SOUNDS.uncloak=new buzz.sound("ogg/decloak_romulan",{formats:["ogg","mp3"]})}
function uncloakevent(){return new CustomEvent("uncloakcomplete",{detail:{time:new Date},bubbles:!0,cancelable:!0})}function transformPoint(a,b){return{x:b.x*a.a+b.y*a.c+a.e,y:b.x*a.b+b.y*a.d+a.f}}function halftone(a){return a==GREEN?HALFGREEN:a==RED?HALFRED:a==WHITE?HALFWHITE:a==BLUE?HALFBLUE:a==YELLOW?HALFYELLOW:a}
var MS=function(a,b){return(new Snap.Matrix).scale(a,b)},MT=function(a,b){return(new Snap.Matrix).translate(a,b)},MR=function(a,b,c){return(new Snap.Matrix).rotate(a,b,c)},C={GREEN:"#0F0",RED:"#F00",WHITE:"#FFF"},P,A={ROLL:{key:"r",color:GREEN},FOCUS:{key:"f",color:GREEN},TARGET:{key:"l",color:BLUE},EVADE:{key:"e",color:GREEN},BOOST:{key:"b",color:GREEN},STRESS:{key:"s",color:RED},CLOAK:{key:"k",color:BLUE},ISTARGETED:{key:"l",color:RED},ASTROMECH:{key:"A",color:YELLOW},CANNON:{key:"C",color:YELLOW},
CREW:{key:"W",color:YELLOW},MISSILE:{key:"M",color:YELLOW},TORPEDO:{key:"P",color:YELLOW},ELITE:{key:"E",color:YELLOW},TURRET:{key:"U",color:YELLOW},UPGRADE:{key:"S",color:YELLOW},CRITICAL:{key:"c",color:RED},SALVAGED:{key:"V",color:YELLOW},BOMB:{key:"B",color:YELLOW},TITLE:{key:"t",color:YELLOW},MOD:{key:"m",color:YELLOW},SYSTEM:{key:"S",color:YELLOW},ILLICIT:{key:"I",color:YELLOW},LASER:{key:"%",color:RED},TURRETLASER:{key:"$",color:RED},BILASER:{key:"%",color:RED},NOTHING:{key:"&nbsp;",color:WHITE}},
AINDEX="ROLL FOCUS TARGET EVADE BOOST STRESS CLOAK ISTARGETED ASTRO CANNON CREW MISSILE TORPEDO ELITE TURRET UPGRADE CRITICAL NOTHING".split(" ");function repeat(a,b){if(1>b)return"";for(var c="";1<b;)b&1&&(c+=a),b>>=1,a+=a;return c+a}function dist(a,b){return(a.x-b.x)*(a.x-b.x)+(a.y-b.y)*(a.y-b.y)}
function Unit(a){this.dead=!1;this.hull=this.agility=this.skill=this.shield=0;this.ship={name:"",select:""};this.id=gid;this.pilotid=-1;var b=this.id;generics["u"+gid]=this;gid++;this.ship.select="<select id='select"+b+"' onchange='generics[\"u"+b+"\"].selectship()' style='width:170px;background:white;text-align:center'>";this.team=a;this.faction=TEAMS[a].faction;this.ship.select+="<option disabled selected>Select unit</option>";for(var c in unitlist)0<=unitlist[c].faction.indexOf(this.faction)&&
(this.ship.select+="<option>"+c+"</option>");this.ship.select+="</select>";this.shipactionList=[];this.dial=[];this.dialselect="<div id='dial"+b+"' class='table'></div>";this.pts="<div class='pts' id='pts"+b+"'></div>";this.text="<div id='text"+b+"' class='details' style='margin:4px'></div>";this.pilotselect="<select onchange='generics[\"u"+b+"\"].selectpilot()' id='name"+b+"' style='background:lightsteelblue;width:170px;text-align:center'></select>";this.name="";this.upgradesno=0;this.upgrades=[];
this.removeupg=[];for(a=0;10>a;a++)this.removeupg[a]=Unit.prototype.defaultremoveupg;this.stats="<div id='stats"+b+"'></div>";this.actions="<div id='actions"+b+"'></div>";this.DEFENSEREROLLD=[];this.ATTACKREROLLA=[];this.ATTACKMODA=[];this.DEFENSEMODD=[]}
Unit.prototype={tosquadron:function(a){var b=this.upg;this.action=this.maneuver=-1;this.actionsdone=[];this.actiondone=this.hasmoved=!1;this.focus=this.reroll=0;this.iscloaked=!1;this.target=0;this.istargeted=[];this.targeting=[];this.criticalresolved=this.hitresolved=this.hasfired=this.evade=this.ionized=this.stress=0;this.m=new Snap.Matrix;this.collision=!1;this.ocollision={overlap:-1,template:0};for(j in b)-1<b[j]&&Upgradefromname(this,UPGRADES[b[j]].name);this.color="REBEL"==this.faction?RED:
"EMPIRE"==this.faction?GREEN:YELLOW;this.img=this.islarge?a.image("png/"+this.ship.img[0],-50*this.scale,-50*this.scale,100*this.scale,100*this.scale).transform("r 90 0 0"):a.image("png/"+this.ship.img[0],-20*this.scale,-20*this.scale,40*this.scale,40*this.scale).transform("r 90 0 0");var c=this.islarge?40:20;this.outline=a.rect(-c,-c,2*c,2*c).attr({fill:"rgba(8,8,8,0.5)",strokeWidth:2});this.skillbar=a.text(1-c,3-c,repeat("u",this.skill)).transform("r -90 0 0").attr({class:"xsymbols",fill:"#fa0"});
this.firebar=a.text(1-c,5-c,repeat("u",this.weapons[0].attack)).transform("r -90 0 0").attr({class:"xsymbols",fill:"#f00"});this.evadebar=a.text(1-c,7-c,repeat("u",this.agility)).transform("r -90 0 0").attr({class:"xsymbols",fill:"#0f0"});this.hullbar=a.text(1-c,9-c,repeat("u",this.hull)).transform("r -90 0 0").attr({class:"xsymbols",fill:"#cc0"});this.shieldbar=a.text(1-c,9-c,repeat("u",this.shield+this.hull)).transform("r -90 0 0").attr({class:"xsymbols",fill:"#0af"});this.gstat=a.group(this.skillbar,
this.firebar,this.evadebar,this.shieldbar,this.hullbar);this.dialspeed=a.text(2+c,3-c,"").attr({class:"dialspeed"});this.dialdirection=a.text(c+8,3-c,"").attr({class:"symbols"});this.actionicon=a.text(c+2,-7,"").attr({class:"symbols",strokeWidth:0});this.sector=a.polygon(3-c,-c,0,0,c-3,-c).attr({fill:this.color,opacity:.5,strokeWidth:0});this.ranges=[];this.sectors=[];this.infoicon=[];for(b=0;4>b;b++)this.infoicon[b]=a.text(c-7,6-c+7*b,A[AINDEX[b+2]].key).attr({class:"xsymbols",fill:A[AINDEX[b+2]].color,
strokeWidth:0});this.g=a.group(this.sector,this.outline,this.img,this.dialspeed,this.dialdirection,this.actionicon,this.infoicon[0],this.infoicon[1],this.infoicon[2],this.infoicon[3],this.gstat);this.g.addClass("unit");this.g.hover(function(){var a=this.g.getBBox(),b=$("#playmat").position(),c=b.left+a.x*$("#playmat").width()/900,a=b.top+(a.y-20)*$("#playmat").height()/900;$(".info").css({left:c,top:a}).html(this.name).appendTo("body").show()}.bind(this),function(){$(".info").hide()}.bind(this));
this.setdefaultclickhandler();for(b in PILOTS[this.pilotid])a=PILOTS[this.pilotid],"function"==typeof a[b]&&(this[b]=a[b]);"undefined"!=typeof this.init&&this.init();this.upgrades.sort(function(a,b){a.isWeapon();a.isBomb();b.isWeapon();b.isBomb();return b-a});this.g.drag(this.dragmove.bind(this),this.dragstart.bind(this),this.dragstop.bind(this))},defaultremoveupg:function(a,b){var c=this.upg[a];$("#upgradetext"+this.id+"_"+a+" div").remove();$("#pts"+this.id+"_"+a).html("");-1!=c&&("undefined"!=
typeof UPGRADES[c].unique&&delete UNIQUE[this.team][UPGRADES[c].name],"undefined"!=typeof UPGRADES[c].uninstall&&UPGRADES[c].uninstall(this),this.showdial(),this.showstats(),this.showactions(),this.upg[a]=-1,b&&($("#upgrade"+this.id+"_"+a+" option").prop("selected",!1),$("#upgrade"+this.id+"_"+a+" option[val=-1]").prop("selected",!0)))},toJSON:function(){var a={};a.name=xws_lookup(this.name);a.points=PILOTS[this.pilotid].points;a.ship=xws_lookup(this.ship.name);for(var b={},c=0;10>c;c++)if(-1!=this.upg[c]){var d=
UPGRADES[this.upg[c]],e=UPGRADE_TYPES[d.type];"undefined"==typeof b[e]&&(b[e]=[]);b[e].push(upg_lookup(d.name))}a.upgrades=b;return a},toASCII:function(){var a;a=""+this.pilotid;for(var b=1;b<this.upgrades.length;b++){for(var c=0;c<UPGRADES.length&&UPGRADES[c].name!=this.upgrades[b].name;c++);a+=","+c}return a},toString2:function(){var a;a="<div>"+("<div><div class='dial' style='border:0;margin:0;padding:0'>"+this.dialselect+"</div></div>");a+="<div><div>"+this.pts+"</div></div>";a+="<div><div class='name'>"+
this.pilotselect+"</div></div>";a+="<div><div>"+this.ship.select+"</div></div>";a+="<div>"+this.stats+"</div>";a+="<div>"+this.actions+"</div>";a+="<div>"+this.text+"</div>";a+="<div id='upgrade"+this.id+"'></div>";return a+="</div></div>"},getagility:function(){return this.agility},getdial:function(){return 0<this.ionized&&!this.islarge||1<this.ionized?[{move:"F1",difficulty:"WHITE"}]:this.dial},showdial:function(){var a=[],b,c,d=this.getdial();$("#move").css({display:"none"});if(phase==PLANNING_PHASE||
phase==SELECT_PHASE1||phase==SELECT_PHASE2){for(b=0;5>=b;b++)for(a[b]=[],c=0;5>=c;c++)a[b][c]="<div></div>";$("#select"+this.id).val();for(b=0;b<d.length;b++){c=d[b];var e=MPOS[c.move][0],f=MPOS[c.move][1];"RED"==c.difficulty&&0<this.stress?a[e][f]="<div></div>":(a[e][f]="<div",phase==PLANNING_PHASE&&(a[e][f]+=" onclick='activeunit.setmaneuver("+b+")'"),a[e][f]+=" class='symbols "+c.difficulty,this.maneuver==b&&(a[e][f]+=" selected"),a[e][f]+="' >"+P[c.move].key+"</div>")}d="";for(b=5;0<=b;b--){d+=
"<div>";d=0<b&&5>b?d+("<div>"+b+"</div>"):d+"<div>&nbsp;</div>";for(c=0;5>=c;c++)d+=a[b][c];d+="</div>\n"}phase==SELECT_PHASE1||phase==SELECT_PHASE2?$("#dial"+this.id).html(d):$("#maneuverdial").html(d)}else phase==ACTIVATION_PHASE&&this.skill==skillturn&&-1<this.maneuver&&!this.hasmoved&&$("#move").css({display:"block"});phase>=PLANNING_PHASE&&(-1==this.maneuver||this.hasmoved)&&(this.dialspeed.attr({text:""}),this.dialdirection.attr({text:""}))},removepilot:function(a){if(-1!=this.pilotid){for(k=
0;10>k;k++)this.removeupg[k].call(this,k,!0);this.uninstall();if("undefined"!=typeof UNIQUE[this.team][this.name])UNIQUE[this.team][this.name](this.name,!1)}1==a&&$("#name"+this.id).empty()},getpilotlist:function(){var a,b=-1,c=$("#select"+this.id).val();$("#name"+this.id).append("<option disabled>Select pilot</option>");for(a=0;a<PILOTS.length;a++)PILOTS[a].unit==c&&PILOTS[a].faction==this.faction&&($("#name"+this.id).append("<option"+(-1==b?" selected":"")+">"+PILOTS[a].name+" ("+PILOTS[a].points+
")</option>"),-1==b&&1!=PILOTS[a].unique&&(b=a))},selectship:function(a,b){var c=a;"undefined"==typeof a&&(c=$("#select"+this.id).val());var d=unitlist[c];this.ship.firesnd=d.firesnd;this.ship.flysnd=d.flysnd;this.ship.code=d.code;this.ship.img=d.img;this.ship.hull=d.hull;this.ship.shield=d.shield;this.scale=d.scale;this.islarge=1==d.islarge?!0:!1;this.agility=d.evade;this.hull=d.hull;this.shield=d.shield;this.ship.name=c;this.dial=d.dial.slice(0);this.shipactionList=d.actionList.slice(0);this.weapons=
[];this.upgrades=[];this.bombs=[];this.lastdrop=-1;Laser(this,d.weapon_type,d.fire);$("#text"+this.id).html("");this.showdial();this.showactions();this.removepilot(!0);this.getpilotlist();this.selectpilot(b)},initupgradelist:function(a,b){for(var c=PILOTS[this.pilotid],d="",e=0;e<UPGRADES.length;e++){var f=UPGRADES[e];"undefined"!=typeof f.faction&&f.faction!=c.faction||"undefined"!=typeof f.ship&&f.ship!=c.unit||"undefined"!=typeof f.ishuge||"undefined"!=typeof f.islarge&&1!=this.islarge||"undefined"!=
typeof f.skillmin&&this.skill<f.skillmin||"undefined"!=typeof f.noupgrades&&-1<c.upgrades.indexOf(f.noupgrades)||("undefined"==typeof f.actionrequired||-1!=this.shipactionList.indexOf(f.actionrequired.toUpperCase()))&&a.match(f.type)&&(d+="<option value='"+e+"'>"+f.name+"</option>")}return d},addupgradetype:function(a,b,c){var d=0;"undefined"!=typeof c&&(d=c);c="<div id='upgradetext"+this.id+"_"+b+"' class='upgrade'>";c+="<span class='pts' id='pts"+this.id+"_"+b+"'></span>";c=c+("<a href='#' class='upgrades "+
("Cannon|Torpedo|Missile"==a?"CannonTorpedoMissile":a)+"'></a>")+("<select id='upgrade"+this.id+"_"+b+"' onchange='generics[\"u"+this.id+'"].selectupgrade("'+a+'",'+b+","+d+")'>");c+="<option value='-1' selected>none</option>";a=this.initupgradelist(a,b);""!=a?(c+=a+"</select></div>",$("#upgrade"+this.id).append(c)):$("#upgrade"+this.id).append("<div id='upgradetext"+this.id+"_"+b+"'></div>")},showstats:function(){$("#stats"+this.id).html("<div class='PS'>"+this.skill+"</div><div class='statfire'>"+
this.weapons[0].attack+"</div><div class='statevade'>"+this.getagility()+"</div><div class='statshield'>"+this.shield+"</div><div class='stathull'>"+this.hull+"</div>")},showactions:function(){for(var a="",b=0;b<this.shipactionList.length;b++)a+="<code class='symbols'>"+A[this.shipactionList[b]].key+"</code>";$("#actions"+this.id).html(a)},selectpilot:function(a){this.removepilot(!1);var b=a;"undefined"==typeof a&&(b=$("#name"+this.id).val());for(a=0;a<PILOTS.length&&0!=b.indexOf(PILOTS[a].name+("SCUM"==
this.team?" (Scum)":""));a++);this.name=PILOTS[a].name;if(a!=PILOTS.length){this.pilotid=a;this.unique=1==PILOTS[a].unique?!0:!1;this.skill=PILOTS[a].skill;this.install="undefined"!=typeof PILOTS[a].install?PILOTS[a].install:function(){};this.uninstall="undefined"!=typeof PILOTS[a].uninstall?PILOTS[a].uninstall:function(){};b=PILOTS[a].upgrades;this.upg=[];for(a=0;10>a;a++)this.upg[a]=-1;$("#upgrade"+this.id).html("");for(a=0;a<b.length;a++)this.addupgradetype(b[a],a);this.addupgradetype("Mod",b.length);
this.addupgradetype("Title",b.length+1);this.upgradesno=b.length+2;this.install(this);if(this.unique){log(this.name+" is a unique pilot");b=UNIQUE[this.team][this.name];if("undefined"!=typeof b)UNIQUE[this.team][this.name](this.name,!0);UNIQUE[this.team][this.name]=function(a,b){b?(log("Only one pilot "+a),this.removepilot(!0),this.getpilotlist(),this.selectpilot()):delete UNIQUE[this.team][a]}.bind(this)}b=PILOTS[this.pilotid].upg;b=PILOT_translation.english[this.name+("SCUM"==this.faction?" (Scum)":
"")];"undefined"==typeof b&&(b="");$("#text"+this.id).html(b);this.showstats();$("#pts"+this.id).html(PILOTS[this.pilotid].points);TEAMS[this.team].updatepoints()}},selectupgrade:function(a,b,c){this.removeupg[b].call(this,b,!1);var d=$("#upgrade"+this.id+"_"+b).val();this.upg[b]=d;if(-1==d)$("#upgrade"+this.id+"_"+b).css({margin:"0px"}),$("#pts"+this.id+"_"+b).html("");else{$("#upgrade"+this.id+"_"+b).css({margin:"0 0 30px 0"});"undefined"!=typeof UPGRADES[d].install&&UPGRADES[d].install(this);if(1==
UPGRADES[d].unique){var e=UPGRADES[d];log(e.name+" is a unique upgrade");if("undefined"!=typeof UNIQUE[this.team][e.name])UNIQUE[this.team][e.name](e.name,!0);UNIQUE[this.team][e.name]=function(a,b){log("Removing unique upgrade "+a);this.obj.removeupg[this.key].call(this.obj,this.key,b);delete UNIQUE[this.team][a]}.bind({key:b,obj:this})}c=UPGRADES[d].points+c;$("#pts"+this.id+"_"+b).html(c);c=UPGRADES[d];$("#upgradetext"+this.id+"_"+b).prepend("<div class='dial details' style='border:0;margin:0;padding:0'>"+
(c.attack?"<b class='statfire'>"+c.attack+"</b>["+c.range[0]+"-"+c.range[1]+"], ":"")+UPGRADE_translation.english[c.name+("Crew"==a?"(Crew)":"")]+"</div>");a=UPGRADES[d].addedaction;"undefined"!=typeof a&&(c=a.toUpperCase(),this.shipactionList.push(c),log("Added action:"+a),this.removeupg[b]=function(a,b){var c=this.shipactionList.indexOf(UPGRADES[this.upg[a]].addedaction.toUpperCase());-1<c&&this.shipactionList.splice(c,1);this.defaultremoveupg(a,b);this.removeupg[a]=this.defaultremoveupg}.bind(this));
a=UPGRADES[d].upgrades;if("undefined"!=typeof a){for(c=0;c<a.length;c++)this.addupgradetype(a[c],this.upgradesno+c,UPGRADES[d].pointsupg);$("#upgrade"+this.id+"_"+b).prop("start",this.upgradesno);this.removeupg[b]=function(a,b){for(var c=UPGRADES[this.upg[a]].upgrades,d=$("#upgrade"+this.id+"_"+a).prop("start"),e=d;e<d+c.length;e++)$("#upgradetext"+this.id+"_"+e).remove(),this.removeupg[e].call(this,e,!0);this.upgradesno-=c.length;this.defaultremoveupg(a,b);this.removeupg[a]=this.defaultremoveupg}.bind(this);
this.upgradesno+=a.length}this.showdial();this.showactions();this.showstats()}TEAMS[this.team].updatepoints()},getattacktable:function(a){return ATTACK[a]},attackroll:function(a){var b,c,d,e,f=this.getattacktable(a),g=0,h=Math.random();for(c=0;c<=a;c++)for(d=0;d<=a-c;d++)for(e=0;e<=a-c-d;e++)if(b=100*c+d+10*e,g+=f[b],g>h)return 100*c+10*e+d;return 0},getdefensetable:function(a){return DEFENSE[a]},defenseroll:function(a){var b,c,d,e=this.getdefensetable(a),f=0,g=Math.random();if(0==a)return 0;for(d=
0;d<=a;d++)for(c=0;c<=a-d;c++)if(b=10*d+c,f+=e[b],f>g)return 10*d+c;return 0},addattackrerolla:function(a,b,c,d,e){e?ATTACKREROLLA.push({org:a,type:b,n:c,req:d}):this.ATTACKREROLLA.push({org:a,type:b,n:c,req:d})},adddefensererolld:function(a,b,c,d,e){e?DEFENSEREROLLD.push({org:a,type:b,n:c,req:d}):this.DEFENSEREROLLD.push({org:a,type:b,n:c,req:d})},addattackmoda:function(a,b,c,d,e){d?ATTACKMODA.push({org:a,req:b,f:c,str:e}):this.ATTACKMODA.push({org:a,req:b,f:c,str:e})},adddefensemodd:function(a,
b,c,d,e){d?DEFENSEMODD.push({org:a,req:b,f:c,str:e}):this.DEFENSEMODD.push({org:a,req:b,f:c,str:e})},setclickhandler:function(a){this.g.unmousedown();this.g.mousedown(a)},setdefaultclickhandler:function(){this.g.unmousedown();this.g.mousedown(function(){if(this!=activeunit){var a=activeunit;this.select();a.unselect()}}.bind(this))},dragmove:function(a,b,c,d){a=900*a/$("#playmat").width();b=900*b/$("#playmat").height();this.dragMatrix=MT(a,b).add(this.m);this.dragged=!0;$(".phasepanel").hide();this.g.transform(this.dragMatrix)},
dragstart:function(a,b,c){this.showhitsector(!1);this.dragged=!1},dragstop:function(a){this.dragged&&(this.m=this.dragMatrix,this.showpanel());this.dragged=!1},isinzone:function(a){a=this.getOutlinePoints(a);for(var b=0;4>b;b++)if(0>a[b].x||900<a[b].x||0>a[b].y||900<a[b].y)return!1;return!0},getOutlinePoints:function(a){if(this.moutline==a)return this.op;this.moutline=a;var b=this.islarge?40:20,c=transformPoint(a,{x:-b,y:-b}),d=transformPoint(a,{x:b,y:-b}),e=transformPoint(a,{x:b,y:b});a=transformPoint(a,
{x:-b,y:b});return this.op=[c,d,e,a]},getOutline:function(a){a=this.getOutlinePoints(a);return s.path("M "+a[0].x+" "+a[0].y+" L "+a[1].x+" "+a[1].y+" "+a[2].x+" "+a[2].y+" "+a[3].x+" "+a[3].y+" Z").attr({display:"none"})},getRangeString:function(a,b){var c=this.islarge?40:20,d=transformPoint(b,{x:-c,y:-100*a-c}),e=transformPoint(b,{x:c,y:-100*a-c}),f=transformPoint(b,{x:100*a+c,y:-c}),g=transformPoint(b,{x:100*a+c,y:c}),h=transformPoint(b,{x:c,y:100*a+c}),l=transformPoint(b,{x:-c,y:100*a+c}),m=transformPoint(b,
{x:-100*a-c,y:c}),p=transformPoint(b,{x:-100*a-c,y:-c}),q=transformPoint(b,{x:50*a+c,y:-100*a-c}),u=transformPoint(b,{x:100*a+c,y:-50*a-c}),n=transformPoint(b,{x:100*a+c,y:50*a+c}),r=transformPoint(b,{x:50*a+c,y:100*a+c}),t=transformPoint(b,{x:-50*a-c,y:100*a+c}),v=transformPoint(b,{x:-100*a-c,y:50*a+c}),w=transformPoint(b,{x:-100*a-c,y:-50*a-c}),c=transformPoint(b,{x:-50*a-c,y:-100*a-c});return"M "+d.x+" "+d.y+" L "+e.x+" "+e.y+" C "+q.x+" "+q.y+" "+u.x+" "+u.y+" "+f.x+" "+f.y+" L "+g.x+" "+g.y+
" C "+n.x+" "+n.y+"  "+r.x+" "+r.y+" "+h.x+" "+h.y+" L "+l.x+" "+l.y+" C "+t.x+" "+t.y+" "+v.x+" "+v.y+" "+m.x+" "+m.y+" L "+p.x+" "+p.y+" C "+w.x+" "+w.y+" "+c.x+" "+c.y+" "+d.x+" "+d.y},getSubRangeString:function(a,b,c){var d=this.islarge?40:20,e=transformPoint(c,{x:-d,y:-100*a-d}),f=transformPoint(c,{x:d,y:-100*a-d}),g=transformPoint(c,{x:100*a+d,y:-d}),h=transformPoint(c,{x:100*a+d,y:d}),l=transformPoint(c,{x:d,y:100*a+d}),m=transformPoint(c,{x:-d,y:100*a+d}),p=transformPoint(c,{x:-100*a-d,y:d}),
q=transformPoint(c,{x:-100*a-d,y:-d}),u=transformPoint(c,{x:50*a+d,y:-100*a-d}),n=transformPoint(c,{x:100*a+d,y:-50*a-d}),r=transformPoint(c,{x:100*a+d,y:50*a+d}),t=transformPoint(c,{x:50*a+d,y:100*a+d}),v=transformPoint(c,{x:-50*a-d,y:100*a+d}),w=transformPoint(c,{x:-100*a-d,y:50*a+d}),x=transformPoint(c,{x:-100*a-d,y:-50*a-d});a=transformPoint(c,{x:-50*a-d,y:-100*a-d});var y="M "+e.x+" "+e.y+" L "+f.x+" "+f.y+" C "+u.x+" "+u.y+" "+n.x+" "+n.y+" "+g.x+" "+g.y+" L "+h.x+" "+h.y+" C "+r.x+" "+r.y+
"  "+t.x+" "+t.y+" "+l.x+" "+l.y+" L "+m.x+" "+m.y+" C "+v.x+" "+v.y+" "+w.x+" "+w.y+" "+p.x+" "+p.y+" L "+q.x+" "+q.y+" C "+x.x+" "+x.y+" "+a.x+" "+a.y+" "+e.x+" "+e.y,e=transformPoint(c,{x:-d,y:-100*b-d}),f=transformPoint(c,{x:d,y:-100*b-d}),g=transformPoint(c,{x:100*b+d,y:-d}),h=transformPoint(c,{x:100*b+d,y:d}),l=transformPoint(c,{x:d,y:100*b+d}),m=transformPoint(c,{x:-d,y:100*b+d}),p=transformPoint(c,{x:-100*b-d,y:d}),q=transformPoint(c,{x:-100*b-d,y:-d}),u=transformPoint(c,{x:50*b+d,y:-100*
b-d}),n=transformPoint(c,{x:100*b+d,y:-50*b-d}),r=transformPoint(c,{x:100*b+d,y:50*b+d}),t=transformPoint(c,{x:50*b+d,y:100*b+d}),v=transformPoint(c,{x:-50*b-d,y:100*b+d}),w=transformPoint(c,{x:-100*b-d,y:50*b+d}),x=transformPoint(c,{x:-100*b-d,y:-50*b-d});a=transformPoint(c,{x:-50*b-d,y:-100*b-d});return y+=" L "+e.x+" "+e.y+" C "+a.x+" "+a.y+" "+x.x+" "+x.y+" "+q.x+" "+q.y+" L "+p.x+" "+p.y+" C "+w.x+" "+w.y+" "+v.x+" "+v.y+" "+m.x+" "+m.y+" L "+l.x+" "+l.y+" C "+t.x+" "+t.y+" "+r.x+" "+r.y+" "+
h.x+" "+h.y+" L "+g.x+" "+g.y+" C "+n.x+" "+n.y+" "+u.x+" "+u.y+" "+f.x+" "+f.y+" L "+e.x+" "+e.y},getSectorString:function(a,b){var c=this.islarge?40:20,d=this.getSectorPoints(a,new Snap.matrix),e=this.getSectorPoints(a,b),f=transformPoint(b,{x:0,y:0}),g=transformPoint(b,{x:d[0].x+c/2*a,y:d[0].y-c*a/2}),h=transformPoint(b,{x:(d[0].x+3*d[1].x)/4,y:d[1].y}),l=transformPoint(b,{x:(3*d[2].x+d[3].x)/4,y:d[2].y}),c=transformPoint(b,{x:d[3].x-c/2*a,y:d[3].y-c/2*a});return"M "+f.x+" "+f.y+" L "+e[0].x+" "+
e[0].y+" C "+g.x+" "+g.y+" "+h.x+" "+h.y+" "+e[1].x+" "+e[1].y+" L "+e[2].x+" "+e[2].y+" C "+l.x+" "+l.y+" "+c.x+" "+c.y+" "+e[3].x+" "+e[3].y+" Z"},getSubSectorString:function(a,b,c){var d=this.islarge?40:20,e=this.getSectorPoints(a,new Snap.matrix),f=this.getSectorPoints(a,c),g=transformPoint(c,{x:e[0].x+d/2*a,y:e[0].y-d*a/2}),h=transformPoint(c,{x:(e[0].x+3*e[1].x)/4,y:e[1].y}),l=transformPoint(c,{x:(3*e[2].x+e[3].x)/4,y:e[2].y}),e=transformPoint(c,{x:e[3].x-d/2*a,y:e[3].y-d/2*a});a="M "+f[0].x+
" "+f[0].y+" C "+g.x+" "+g.y+" "+h.x+" "+h.y+" "+f[1].x+" "+f[1].y+" L "+f[2].x+" "+f[2].y+" C "+l.x+" "+l.y+" "+e.x+" "+e.y+" "+f[3].x+" "+f[3].y;e=this.getSectorPoints(b,new Snap.matrix);f=this.getSectorPoints(b,c);g=transformPoint(c,{x:e[0].x+d/2*b,y:e[0].y-d*b/2});h=transformPoint(c,{x:(e[0].x+3*e[1].x)/4,y:e[1].y});l=transformPoint(c,{x:(3*e[2].x+e[3].x)/4,y:e[2].y});e=transformPoint(c,{x:e[3].x-d/2*b,y:e[3].y-d/2*b});return a+="L "+f[3].x+" "+f[3].y+" C "+e.x+" "+e.y+" "+l.x+" "+l.y+" "+f[2].x+
" "+f[2].y+" L "+f[1].x+" "+f[1].y+" C "+h.x+" "+h.y+" "+g.x+" "+g.y+" "+f[0].x+" "+f[0].y+" Z"},getSectorPoints:function(a,b){var c=this.islarge?40:20,d=Math.sqrt((c-3)*(c-3)+c*c),e=transformPoint(b,{x:-.95*(d+100*a)/Math.sqrt(1+c*c/(c-3)/(c-3)),y:-(d+100*a)/Math.sqrt(1+(c-3)*(c-3)/c/c)}),f=transformPoint(b,{x:-c+3,y:-c-100*a}),g=transformPoint(b,{x:c-3,y:-c-100*a}),c=transformPoint(b,{x:.95*(d+100*a)/Math.sqrt(1+c*c/(c-3)/(c-3)),y:-(d+100*a)/Math.sqrt(1+(c-3)*(c-3)/c/c)});return[e,f,g,c]},setmaneuver:function(a){"RED"==
this.getdial()[a].difficulty&&0<this.stress||(this.maneuver=a,record(this.id,"this.maneuver="+a),enablenextphase(),this.showdial(),this.showmaneuver())},nextmaneuver:function(){this.maneuver=0>this.maneuver?0:this.maneuver==this.dial.length-1?0:this.maneuver+1;"RED"==this.getdial()[this.maneuver].difficulty&&0<this.stress&&this.nextmaneuver();enablenextphase();this.showdial()},prevmaneuver:function(){this.maneuver=0>this.maneuver?this.dial.length-1:0==this.maneuver?this.dial.length-1:this.maneuver-
1;"RED"==this.getdial()[this.maneuver].difficulty&&0<this.stress&&this.prevmaneuver();enablenextphase();this.showdial()},nextaction:function(){this.action=-1==this.action?0:this.action==this.actionList.length-1?0:this.action+1},prevaction:function(){this.action=-1==this.action?0:0==this.action?this.actionList.length-1:this.action-1},turn:function(a){this.m.add(MR(a,0,0));this.show()},select:function(){waitingforaction.isexecuting||(activeunit=this,$("#"+this.id).addClass("selected"),this.show(),center(this))},
unselect:function(){this!=activeunit&&($("#"+this.id).removeClass("selected"),this.showoutline(),this.showmaneuver())},getocollisions:function(a,b,c,d){var e,f=[],g={overlap:-1,template:0},h=this.getOutline(b);for(e=0;e<OBSTACLES.length;e++)if(this.isintersecting(OBSTACLES[e].getOutlinePoints(),h)){h.remove();g.overlap=e;break}for(b=0;b<=d;b++)e=c.getPointAtLength(b),f.push(transformPoint(a,e));c=[];for(a=0;a<f.length;a++)for(e=0;e<OBSTACLES.length;e++)if(e!=g.overlap&&-1==c.indexOf(e))for(d=OBSTACLES[e].getOutlinePoints(),
b=0;b<d.length;b++){var l=d[b].x-f[a].x,m=d[b].y-f[a].y;if(100>=l*l+m*m){c.push(e);g.template++;break}}h.remove();return g},iscollidingunit:function(a,b){var c=this.getOutline(a),d=b.getOutline(b.m),e=0<Snap.path.intersection(c,d).length;this.islarge&&(e=e||this.isinoutline(c,b,b.m));b.islarge&&(e=e||b.isinoutline(d,this,a));c.remove();d.remove();return e},iscollidinganyunit:function(a){var b;for(b=0;b<squadron.length;b++){var c=squadron[b];if(c!=this&&this.iscollidingunit(a,c))return this.collides=
c,!0}return!1},getpathmatrix:function(a,b){var c=P[b].path.transform(this.m).attr({display:"none"}),d=c.getTotalLength(),c=c.getPointAtLength(d);a.add(MT(c.x,c.y)).add(MR(c.alpha-90,0,0));return a},getpossibleoutline:function(a){var b=this.getOutline(a).attr({fill:this.color,opacity:.5,display:"block"}),c=!0;if(!this.isinzone(a))return b.attr({display:"none"}),{ol:b,b:!1};for(a=0;a<squadron.length;a++){var d=squadron[a];if(d!=this){var d=d.getOutline(d.m),e=Snap.path.intersection(b,d);d.remove();
if(0<e.length){c=!1;b.attr({display:"none"});break}}}if(c)for(a=0;a<OBSTACLES.length;a++)if(this.isintersecting(OBSTACLES[a].getOutlinePoints(),b)){c=!1;b.attr({display:"none"});break}return{ol:b,b:c}},isTurret:function(a){return"Turretlaser"==a.type},updateactionlist:function(){var a;this.actionList=[];for(a=0;a<this.shipactionList.length;a++){var b=this.shipactionList[a];-1==this.actionsdone.indexOf(b)&&this.actionList.push(b)}for(a=0;a<this.upgrades.length;a++)b=this.upgrades[a],b.isactive&&"function"==
typeof b.action&&b.candoaction()&&this.actionList.push(b.type.toUpperCase())},addevadetoken:function(){this.evade++;this.show();record(this.id,"TE")},addevade:function(){this.addevadetoken();this.endaction();return!0},addfocustoken:function(){this.focus++;this.show();record(this.id,"TF")},addfocus:function(){this.addfocustoken();this.endaction();return!0},addstress:function(){this.stress++;record(this.id,"TS");this.show()},addiontoken:function(){this.ionized++;record(this.id,"TI");this.show()},removeiontoken:function(){this.ionized--;
record(this.id,"RI");this.show()},dies:function(){var a;record(this.i,"D");$("#"+this.id).attr("onclick","");$("#"+this.id).addClass("dead");$("#"+this.id).html(""+this);for(a=0;a<squadron.length;a++)if(squadron[a]==this){squadron.splice(a,1);break}this.dead=!0;this.m=MT(-60,-60);log(this.name+" has exploded !");this.show();TEAMS[this.team].checkdead()&&win();SOUNDS.explode.play()},canbedestroyed:function(){return skillturn!=this.skill?!0:!1},checkdead:function(){return 0>=this.hull||!this.isinzone(this.m)?
(this.dies(),!0):!1},cancelhit:function(a,b,c){return a>b?a-b:0},cancelcritical:function(a,b,c){return a>b?a-b:0},evadeattack:function(a){var b=$(".hitreddice").length,c=$(".criticalreddice").length,d=$(".evadegreendice").length,e=$(".evadegreen").length,b=a.weapons[a.activeweapon].modifydamagegiven(10*c+b),c=Math.floor(b/10),f=b-=10*c,b=this.cancelhit(b,d,a),d=d-(f-b),f=b,b=b>=e?b-e:0,e=e-(f-b),c=this.cancelcritical(c,d,a);return 10*(c>=e?c-e:0)+b},declareattack:function(a,b){targetunit=b;this.activeweapon=
a;this.weapons[a].declareattack(b);log(this.name+" attacks "+b.name+" with "+this.weapons[a].name);b.isattackedby(a,this)},isattackedby:function(a,b){},modifydamageassigned:function(a,b){return a},ishit:function(a,b){},resolvedamage:function(){this.fireline.remove();this.playfiresnd();var a=targetunit.evadeattack(this),a=this.weapons[this.activeweapon].modifydamageassigned(a,targetunit),a=targetunit.modifydamageassigned(a,this),b=Math.floor(a/10),a=a-10*b;this.hasdamaged=!0;0<b+a&&(b+a<targetunit.shield?
log(targetunit.name+" lost "+(b+a)+" <p class='cshield'></p>"):0<targetunit.shield&&log(targetunit.name+" lost all <p class='cshield'></p>"),targetunit.ishit(this),this.hitresolved+=a,this.criticalresolved+=b,targetunit.resolvehit(a),targetunit.resolvecritical(b));targetunit.endbeingattacked(b,a);this.weapons[this.activeweapon].endattack(b,a);this.endattack(b,a);targetunit.canbedestroyed(skillturn)&&targetunit.checkdead();this.cleanupattack()},cleanupattack:function(){log("calling nextstep from cleanup");
nextstep()},endround:function(){this.focus=this.evade=0;this.showinfo()},playfiresnd:function(){var a=targetunit.g.getBBox(),b=transformPoint(this.m,{x:0,y:-(this.islarge?40:20)}),c=s.path("M "+b.x+" "+b.y+" L "+(a.x+a.w/2)+" "+(a.y+a.h/2)).attr({stroke:this.color,strokeWidth:2}),d=setInterval(function(){c.remove();clearInterval(d)},200);"undefined"!=typeof this.weapons[this.activeweapon].firesnd?SOUNDS[this.weapons[this.activeweapon].firesnd].play():SOUNDS[this.ship.firesnd].play();record(this.id,
"playfiresnd()")},endattack:function(a,b){for(i=0;i<DICES.length;i++)$("."+DICES[i]+"dice").remove();this.show()},endbeingattacked:function(a,b){this.show();this.activeweapon=-1},usecloak:function(a){waitingforaction.isexecuting||phase!=ACTIVATION_PHASE||0!=this.stress||this.hasmoved||this.resolveuncloak()},usestress:function(a){},usefocusattack:function(a){this.removefocustoken();this.show();a=$(".focusreddice").length;$(".focusreddice").remove();for(i=0;i<a;i++)$("#attack").prepend("<td class='hitreddice'></td>");
$("#attack > .xfocustoken").remove()},usefocus:function(a){if(phase==COMBAT_PHASE)if(this==activeunit)this.usefocusattack(a);else if(this==targetunit)for(targetunit.removefocustoken(),targetunit.show(),a=$(".focusgreendice").length,$(".focusgreendice").remove(),$("#defense > .xfocustoken").remove(),i=0;i<a;i++)$("#defense").prepend("<td class='evadegreendice'></td>")},removetarget:function(a){var b;b=a.istargeted.indexOf(this);-1<b&&a.istargeted.splice(b,1);this.targeting.splice(a);a.show();0==this.targeting.length&&
$("#attack > .xtargettoken").remove()},usetarget:function(){return phase==COMBAT_PHASE&&activeunit==this&&-1<this.targeting.indexOf(targetunit)?(this.removetarget(targetunit),reroll(10,!0,99,""),!0):!1},useevade:function(){phase==COMBAT_PHASE&&this==targetunit&&(this.removeevadetoken(),this.show(),$("#defense > .xevadetoken").remove(),$("#defense").prepend("<td class='evadegreen'></td>"))},removeevadetoken:function(){record(this.id,"RE");this.evade--;this.show()},removefocustoken:function(){record(this.id,
"RF");this.focus--;this.show()},resolveactionmove:function(a,b,c,d){var e;this.pos=[];var f=function(a,b,d){for(e=0;e<this.pos.length;e++)this.pos[e].ol.remove();c&&(this.m=a);d(this,b);this.show()}.bind(this);for(e=0;e<a.length;e++){var g=this.getpossibleoutline(a[e]);d||g.b?(g.ol.attr({display:"block"}),this.pos.push({ol:g.ol,k:e})):g.ol.remove()}if(0<this.pos.length)if(1==this.pos.length)f(this.pos[0].ol,this.pos[0].k,b);else for(e=0;e<this.pos.length;e++)(function(c){var d=this.pos[c];d.ol.hover(function(){this.pos[c].ol.attr({stroke:this.color,
strokeWidth:"4px"})}.bind(this),function(){this.pos[c].ol.attr({strokeWidth:"0px"})}.bind(this));d.ol.click(function(){f(a[this.pos[c].k],this.pos[c].k,b)}.bind(this))}).call(this,e);else f(this.m,-1,b)},resolveactionselection:function(a,b){var c;this.pos=[];var d=function(d){for(c=0;c<a.length;c++)a[c].outline.attr({fill:"rgba(8,8,8,0.5)"}),a[c].setdefaultclickhandler();b(d)}.bind(this);if(0==a.length)d(-1);else if(1==a.length)d(0);else for(c=0;c<a.length;c++)a[c].outline.attr({fill:"rgba(100,100,100,0.8)"}),
function(b){a[b].setclickhandler(function(){d(b)})}(c)},resolveboost:function(){waitingforaction.add(function(){this.resolveactionmove([this.getpathmatrix(this.m.clone().add(MT(0,this.islarge?-20:0)),"F1").add(MT(0,-20)),this.getpathmatrix(this.m.clone().add(MT(0,this.islarge?-20:0)),"BL1").add(MT(0,-20)),this.getpathmatrix(this.m.clone().add(MT(0,this.islarge?-20:0)),"BR1").add(MT(0,-20))],function(a,b){this.endaction()},!0)}.bind(this));return!0},resolveuncloak:function(){var a=this.getpathmatrix(this.m.clone().add(MR(90,
0,0)).add(MT(0,this.islarge?-20:0)),"F2").add(MR(-90,0,0)).add(MT(0,-20)),b=this.getpathmatrix(this.m.clone().add(MR(-90,0,0)).add(MT(0,this.islarge?-20:0)),"F2").add(MR(90,0,0)).add(MT(0,20)),c=this.getpathmatrix(this.m.clone(),"F2");waitingforaction.add(function(){this.resolveactionmove([a.clone().add(MT(0,0)),a.clone().add(MT(0,20)),a.clone().add(MT(0,40)),c,b.clone().add(MT(0,0)),b.clone().add(MT(0,-20)),b.clone().add(MT(0,-40))],function(a,b){a.agility-=2;a.iscloaked=!1;SOUNDS.uncloak.play()},
!0)}.bind(this));nextstep();return!0},resolveroll:function(){waitingforaction.add(function(){var a=this.getpathmatrix(this.m.clone().add(MR(90,0,0)).add(MT(0,this.islarge?-20:0)),"F1").add(MR(-90,0,0)).add(MT(0,-20)),b=this.getpathmatrix(this.m.clone().add(MR(-90,0,0)).add(MT(0,this.islarge?-20:0)),"F1").add(MR(90,0,0)).add(MT(0,-20));this.resolveactionmove([a.clone().add(MT(0,0)),a.clone().add(MT(0,20)),a.clone().add(MT(0,40)),b.clone().add(MT(0,0)),b.clone().add(MT(0,20)),b.clone().add(MT(0,40))],
function(a,b){this.endaction()},!0)}.bind(this));return!0},addtarget:function(a){for(var b=0;b<this.targeting.length;b++)this.removetarget(this.targeting[b]);this.targeting.push(a);a.istargeted.push(this);a.show();this.show()},gettargetableunits:function(a){var b=[],c;for(c=0;c<squadron.length;c++)squadron[c].team!=this.team&&this.getrange(squadron[c])<=a&&b.push(squadron[c]);return b},selectnearbyunits:function(a,b){for(var c=[],d=0;d<squadron.length;d++)log(this.name+":"+squadron[d].name+" "+b(this,
squadron[d])+" "+(this.getrange(squadron[d])<=a)),b(this,squadron[d])&&this.getrange(squadron[d])<=a&&c.push(squadron[d]);return c},resolvetarget:function(){var a;a=this.gettargetableunits(3);return 0<a.length?(log("<b>["+this.name+"] select target to lock</b>"),waitingforaction.add(function(){this.resolveactionselection(a,function(b){0<=b&&this.addtarget(a[b]);this.endaction()}.bind(this))}.bind(this)),!0):!1},resolvecloak:function(){this.iscloaked=!0;this.agility+=2;SOUNDS.cloak.play();this.endaction();
return!0},endaction:function(){this.actiondone=!0;this.action=-1;log("END ACTION");nextstep();return!0},resolveaction:function(){var a;$("#actiondial").empty();-1==this.action?a="NOTHING":(a=this.actionList[this.action],this.actionsdone.push(a));if("BOOST"==a)return this.resolveboost();if("ROLL"==a)return this.resolveroll();if("CLOAK"==a)return this.resolvecloak();if("FOCUS"==a)return this.addfocus();if("EVADE"==a)return this.addevade();if("TARGET"==a)return this.resolvetarget();var b,c=this.shipactionList.length;
for(b=0;b<this.upgrades.length;b++){var d=this.upgrades[b];if("function"==typeof d.action&&d.isactive){if(d.type.toUpperCase()==a&&this.action==c)return d.action();c++}}this.endaction();return!0},getattackreroll:function(a,b){return 0},modifyattackroll:function(a,b){return a},getdefensereroll:function(a,b){return 0},evaluatetohit:function(a,b){var c=this.gethitrange(a,b);if(b!=this&&3>=c&&0<c){var c=this.getattackstrength(a,b),d=b.getdefensestrength(a,this);-1<this.targeting.indexOf(b)?this.reroll=
10:this.reroll=this.weapons[a].getattackreroll(b)+this.getattackreroll(a,b);return tohitproba(this,b,this.getattacktable(c),b.getdefensetable(d),c,d)}return{proba:[],tohit:0,meanhit:0,meancritical:0,tokill:0}},canfire:function(){var a=this.gethitrangeallunits();return 0==this.hasfired&&(0<a[1].length||0<a[2].length||0<a[3].length)&&!this.iscloaked&&-1==this.ocollision.overlap},getattackstrength:function(a,b){return this.weapons[a].getattack()+this.weapons[a].getattackbonus(b)},getdefensestrength:function(a,
b){var c=this.getagility(),d=this.getoutlinerange(this.m,b).o?1:0;0<d&&log(this.name+" +"+d+" defense for obstacle");return c+b.weapons[a].getdefensebonus(this)+d},getattackmodtokens:function(a,b){var c="",d,e;for(me=0;me<squadron.length&&squadron[me]!=this;me++);for(d=0;d<ATTACKMODA.length;d++){var f=ATTACKMODA[d];f.req(a,b)&&(c+="<td id='moda"+d+"' class='"+f.str+"modtokena' onclick='modroll(ATTACKMODA["+d+"].f,"+b+","+d+")' title='modify roll ["+f.org.name.replace(/\'/g,"&#39;")+"]'></td>")}for(e=
0;e<this.ATTACKMODA.length;e++)f=this.ATTACKMODA[e],f.req(a,b)&&(c+="<td id='moda"+(d+e)+"' class='"+f.str+"modtokena' onclick='modroll(squadron["+me+"].ATTACKMODA["+e+"].f,"+b+","+(d+e)+")' title='modify roll ["+f.org.name.replace(/\'/g,"&#39;")+"]'></td>");return c},getdefensemodtokens:function(a,b){var c="",d,e;for(me=0;me<squadron.length&&squadron[me]!=this;me++);for(d=0;d<DEFENSEMODD.length;d++){var f=DEFENSEMODD[d];f.req(a,b)&&(c+="<td id='modd"+d+"' class='"+f.str+"modtokend' onclick='modrolld(DEFENSEMODD["+
d+"].f,"+b+","+d+")' title='modify roll ["+f.org.name.replace(/\'/g,"&#39;")+"]'></td>")}for(e=0;e<this.DEFENSEMODD.length;e++)f=this.DEFENSEMODD[e],f.req(a,b)&&(c+="<td id='modd"+(d+e)+"' class='"+f.str+"modtokend' onclick='modrolld(squadron["+me+"].DEFENSEMODD["+e+"].f,"+b+","+(d+e)+")' title='modify roll ["+f.org.name.replace(/\'/g,"&#39;")+"]'></td>");return c},getattackrerolltokens:function(){for(var a="",b=function(a,b){var c=0,d=a.n();-1<a.type.indexOf("blank")&&(c+=d);-1<a.type.indexOf("focus")&&
(c+=10*d);-1<a.type.indexOf("hit")&&(c+=100*d);-1<a.type.indexOf("critical")&&(c+=1E3*d);return"<td id='rerolla"+b+"' class='tokens' onclick='reroll("+d+",true,"+c+","+b+")' title='"+d+" rerolls ["+a.org.name.replace(/\'/g,"&#39;")+"]'>R"+d+"</td>"},c=0;c<ATTACKREROLLA.length;c++){var d=ATTACKREROLLA[c];d.req(this,this.weapons[this.activeweapon],targetunit)&&(a+=b(d,c))}for(c=0;c<this.ATTACKREROLLA.length;c++)d=this.ATTACKREROLLA[c],d.req(this.weapons[this.activeweapon],targetunit)&&(a+=b(d,c+ATTACKREROLLA.length));
return a},getdefensererolltokens:function(){for(var a="",b=function(a,b){var c=0,d=a.n();-1<a.type.indexOf("blank")&&(c+=d);-1<a.type.indexOf("focus")&&(c+=10*d);-1<a.type.indexOf("evade")&&(c+=100*d);return"<td id='rerolld"+b+"' class='tokens' onclick='reroll("+d+",false,"+c+","+b+")' title='"+d+" rerolls ["+a.org.name.replace(/\'/g,"&#39;")+"]'>R"+d+"</td>"},c=0;c<DEFENSEREROLLD.length;c++){var d=DEFENSEREROLLD[c];d.req(this,this.weapons[this.activeweapon],targetunit)&&(a+=b(d,c))}for(c=0;c<targetunit.DEFENSEREROLLD.length;c++)d=
targetunit.DEFENSEREROLLD[c],d.req(this.weapons[this.activeweapon],this)&&(a+=b(d,c+DEFENSEREROLLD.length));return a},resolveattack:function(a,b){var c;this.gethitrange(a,b);var d=this.getattackstrength(a,b),e=b.getdefensestrength(a,this);this.hasfired++;this.hasdamaged=!1;$("#combatdial").show();c=b.g.getBBox();var f=transformPoint(this.m,{x:0,y:-(this.islarge?40:20)});this.fireline=s.path("M "+f.x+" "+f.y+" L "+(c.x+c.w/2)+" "+(c.y+c.h/2)).attr({stroke:this.color,strokeWidth:2,strokeDasharray:100,
"class":"animated"});this.select();b.unselect();for(c=0;c<squadron.length&&squadron[c]!=this;c++);this.showattackroll(this.attackroll(d),d,c);b.showdefenseroll(b.defenseroll(e),e,c);this.show()},showattackroll:function(a,b,c){var d;$("#attackdial").empty();$("#dtokens").hide();$("#defense").hide();for(d=0;d<DICES.length;d++)$("."+DICES[d]+"dice").remove();$("#attack").html(this.getusabletokens(c,!0)+this.getattackrerolltokens()+this.getattackmodtokens(a,b));c=Math.floor(a/100);for(d=0;d<c;d++)$("#attack").prepend("<td class='focusreddice'></td>");
var e=Math.floor(a/10)%10;for(d=0;d<e;d++)$("#attack").prepend("<td class='criticalreddice'></td>");a%=10;for(d=0;d<a;d++)$("#attack").prepend("<td class='hitreddice'></td>");for(d=0;d<b-a-e-c;d++)$("#attack").prepend("<td class='blankreddice'></td>");$("#atokens").html('<button onclick=\'$("#defense").show(); $("#dtokens").show();$("#atokens").empty()\'>Done</button>')},showdefenseroll:function(a,b,c){var d;for(d=0;d<squadron.length&&squadron[d]!=this;d++);$("#defense").html(this.getusabletokens(d,
!0)+this.getdefensererolltokens()+this.getdefensemodtokens(a,b));$("#dtokens").html('<button onclick=\'$("#combatdial").hide();squadron['+c+"].resolvedamage()'>Fire!</button>");d=Math.floor(a/10);for(c=0;c<d;c++)$("#defense").prepend("<td class='focusgreendice'></td>");a%=10;for(c=0;c<a;c++)$("#defense").prepend("<td class='evadegreendice'></td>");for(c=0;c<b-a-d;c++)$("#defense").prepend("<td class='blankgreendice'></td>")},getmatrixwithmove:function(a,b){var c=a.getTotalLength(),d=this.m.clone();
if(this.islarge)if(20>=b)d.add(MT(0,-b));else{var c=b>c+20?b-c-20:0,e=a.getPointAtLength(b-c-20);d.add(MT(e.x,-20+e.y)).add(MR(e.alpha-90,0,0)).add(MT(0,-c))}else e=a.getPointAtLength(b),d.add(MT(e.x,e.y)).add(MR(e.alpha-90,0,0));return d},removestresstoken:function(){this.stress--;record(this.id,"RS");this.show()},handledifficulty:function(a){"RED"==a?this.addstress():"GREEN"==a&&0<this.stress&&this.removestresstoken()},completemaneuver:function(a,b,c){var d=P[b].path,e=d.transform(this.m).attr({display:"none"});
e.appendTo(s);var f=e.getTotalLength();this.collision=!1;this.futurem=new Snap.matrix;var g,h;this.showhitsector(!1);movePoint=e.getPointAtLength(f);this.islarge&&(f+=40);h=this.m;g=this.getmatrixwithmove(e,f);if(this.iscollidinganyunit(g))for(log(this.name+"  collides with "+this.collides.name+": no action"),this.collision=!0;0<f&&this.iscollidinganyunit(g);)g=this.getmatrixwithmove(e,f),--f;this.m=g;this.ocollision=this.getocollisions(h,this.m,d,f);-1<this.ocollision.overlap&&log(this.name+" overlaps obstacle: no action, cannot attack");
0<this.ocollision.template&&log(this.name+" template overlaps obstacle: no action");0<f?(SOUNDS[this.ship.flysnd].play(),Snap.animate(0,f,function(a){var b=this.m;this.m=h;g=this.getmatrixwithmove(e,a);this.m=b;this.g.transform(g)}.bind(this),TIMEANIM*f/200,mina.linear,function(){this.collision?record(this.id,"M"+b+":"+f):a.match(/K\d|SR\d|SL\d/)?(this.m.add(MR(180,0,0)),record(this.id,"M"+b+":"+f+":R")):record(this.id,"M"+b+":"+f);this.handledifficulty(c);this.maneuver=-1;this.show();e.remove();
(-1<this.ocollision.overlap||0<this.ocollision.template)&&this.resolveocollision();this.endmaneuver()}.bind(this))):(log(this.name+" cannot move"),this.handledifficulty(c),this.maneuver=-1,this.show(),e.remove(),this.endmaneuver())},resolvemaneuver:function(){$("#activationdial").empty();if(!(0>this.maneuver||this.hasmoved)){this.hasmoved=!0;var a=this.getdial()[this.maneuver].move,b=this.getdial()[this.maneuver].difficulty;"F0"==a?(this.handledifficulty(b),this.endmaneuver()):this.completemaneuver(a,
a,b)}},endmaneuver:function(){this.ionized=0;this.hasmoved=!0;this.checkdead()?(this.shield=this.hull=0,nextstep()):this.candoaction()&&this.timeforaction()&&this.showaction();this.showstats()},candoaction:function(){return 0<this.stress||0<this.collision||0<this.ocollision.template||-1<this.ocollision.overlap?!1:!0},canuncloak:function(){return!this.hasmoved&&this.iscloaked&&phase==ACTIVATION_PHASE},selecttargetforattack:function(a){var b=this.weapons[a].getrangeallunits(),c,d=[];for(c=0;c<b.length;c++)b[c].team!=
this.team&&d.push(b[c]);if(0==d.length)return!1;this.resolveactionselection(d,function(b){0<=b&&(this.declareattack(a,d[b]),this.resolveattack(a,d[b]))}.bind(this));return!0},showattack:function(){var a="",b=[],c,d,e;$("#attackdial").hide();phase==COMBAT_PHASE&&skillturn==this.skill&&log(this.name+" show attack ?"+!waitingforaction.isexecuting);if(phase==COMBAT_PHASE&&!waitingforaction.isexecuting&&skillturn==this.skill&&this.canfire()){var f=this.gethitrangeallunits();$("#attackdial").empty();for(c=
1;3>=c;c++)for(d=0;d<f[c].length;d++)for(e=0;e<f[c][d].wp.length;e++){var g=f[c][d].wp[e];-1==b.indexOf(g)&&b.push(g)}for(c=0;c<b.length;c++)e=A[this.weapons[b[c]].type.toUpperCase()],a+="<div class='symbols "+e.color+"' onclick='activeunit.selecttargetforattack("+b[c]+")'>"+e.key+"</div>";a+="<button onclick='activeunit.hasfired++;activeunit.show();'>Skip</button>";$("#attackdial").html("<div>"+a+"</div>").show()}},candotarget:function(){return 0<this.gettargetableunits(3).length},candofocus:function(){return!0},
candoevade:function(){return!0},candropbomb:function(){return this.lastdrop!=round&&!this.hasmoved&&this.skill==skillturn&&phase==ACTIVATION_PHASE},addactivationdial:function(a,b,c,d){this.activationdial.push({pred:a,action:b,html:c,elt:d})},updateactivationdial:function(){this.activationdial=[];this.addactivationdial(function(){return this.canuncloak()}.bind(this),function(){this.usecloak()}.bind(this),A.CLOAK.key,$("<div>").attr({class:"symbols"}));if(this.candropbomb())for(var a=0;a<this.bombs.length;a++){var b=
this.bombs[a];this.addactivationdial(function(){return this.isactive}.bind(b),function(){this.unit.lastdrop=round;$(".bombs").remove();this.drop(this.getbomblocation());this.unit.showactivation()}.bind(b),A.BOMB.key,$("<div>").attr({class:"symbols"}))}return this.activationdial},showactivation:function(){var a=this.updateactivationdial();$("#activationdial").html("<div></div>");for(var b=0;b<a.length;b++){var c=a[b];c.pred()&&c.elt.appendTo("#activationdial > div").click(c.action).html(c.html)}this.timeformaneuver()&&
$("<button>").html("Move").click(function(){this.resolvemaneuver()}.bind(this)).appendTo("#activationdial > div")},freeaction:function(a){this.tfa=this.timeforaction;this.ea=this.endaction;this.timeforaction=function(){return!0};this.endaction=function(){this.endaction=this.ea;this.timeforaction=this.tfa;this.show();a();return!1};this.timeforaction()&&this.showaction()},showaction:function(){var a="",b;$("#actiondial").empty();if(!waitingforaction.isexecuting){this.updateactionlist();for(b=0;b<squadron.length&&
squadron[b]!=this;b++);if(this.candoaction()){var c;for(c=0;c<this.actionList.length;c++){var d=this.actionList[c];if("TARGET"!=d||this.candotarget())if("FOCUS"!=d||this.candofocus())if("EVADE"!=d||this.candoevade())a+="<div class='symbols' onclick='activeunit.action="+c+";squadron["+b+"].resolveaction()'>"+A[d].key+"</div>"}}""!=a&&(a+="<button onclick='activeunit.action=-1;squadron["+b+"].resolveaction()'>Skip</button>",$("#actiondial").html("<div>"+a+"</div>").show());this.action<this.actionList.length&&
-1<this.action?(d=this.actionList[this.action],b=A[d].color,this.actionicon.attr({fill:this==activeunit?b:halftone(b)})):this.actionicon.attr({text:""});return""!=a?!0:!1}},showinfo:function(){var a=0,b;0<this.focus&&this.infoicon[a++].attr({text:A.FOCUS.key,fill:A.FOCUS.color});0<this.evade&&this.infoicon[a++].attr({text:A.EVADE.key,fill:A.EVADE.color});1==this.iscloaked&&this.infoicon[a++].attr({text:A.CLOAK.key,fill:A.CLOAK.color});0<this.targeting.length&&this.infoicon[a++].attr({text:A.TARGET.key,
fill:A.TARGET.color});0<this.istargeted.length&&this.infoicon[a++].attr({text:A.ISTARGETED.key,fill:A.ISTARGETED.color});0<this.stress&&this.infoicon[a++].attr({text:A.STRESS.key,fill:A.STRESS.color});0<this.ionized&&this.infoicon[a++].attr({text:"Z",fill:A.STRESS.color});for(b=a;4>b;b++)this.infoicon[a++].attr({text:""})},showoutline:function(){this.outline.attr({stroke:activeunit==this?this.color:halftone(this.color)})},endcombatphase:function(){this.hasfired=0},beginplanningphase:function(){},
beginactivationphase:function(){this.showmaneuver()},timetoshowmaneuver:function(){return-1<this.maneuver},showmaneuver:function(){if(this.timetoshowmaneuver()){var a=this.getdial()[this.maneuver],b=C[a.difficulty];activeunit!=this&&(b=halftone(b));this.dialspeed.attr({text:P[a.move].speed,fill:b});this.dialdirection.attr({text:P[a.move].key,fill:b})}},beginactivation:function(){this.show()},endactivationphase:function(){this.actionsdone=[]},begincombatphase:function(){},beginattack:function(){},
toString:function(){if(phase==SELECT_PHASE1||phase==SELECT_PHASE2&&2==this.team)return this.toString2();var a,b;for(a=0;a<squadron.length&&this!=squadron[a];a++);a==squadron.length&&(a=-1);str=-1==a?"<div class='dead '>":"<div>";b=8+2*this.upgrades.length;this.hull+this.shield<=b?(str+="<div class='vertical stat'>",str+="<div class='hull'>"+repeat("u ",this.hull)+"</div>",str+="<div class='shield'>"+repeat("u ",this.shield)+"</div></div>"):this.hull>b?(str+="<div class='vertical stat'>",str+="<div class='hull'>"+
repeat("u ",b)+"</div></div>",this.hull<=2*b?(str+="<div class='vertical stat2'>",str+="<div class='hull'>"+repeat("u ",this.hull-b)+"</div>",this.shield+this.hull<=2*b?str+="<div class='shield'>"+repeat("u ",this.shield)+"</div></div>":(str+="<div class='shield'>"+repeat("u ",2*b-this.hull)+"</div></div>",str+="<div class='vertical stat3'>",str+="<div class='shield'>"+repeat("u ",this.shield-2*b+this.hull)+"</div></div>")):(str+="<div class='vertical stat2'><div class='hull'>"+repeat("u ",b)+"</div></div>",
str+="<div class='vertical stat3'><div class='hull'>"+repeat("u ",this.hull-2*b)+"</div>",str+="<div class='shield'>"+repeat("u ",this.shield)+"</div></div>")):(str+="<div class='vertical stat'><div class='hull'>"+repeat("u ",this.hull)+"</div>",str+="<div class='shield'>"+repeat("u ",b-this.hull)+"</div></div>",str+="<div class='vertical stat2'><div class='shield'>"+repeat("u ",this.shield-b+this.hull)+"</div></div>");str+="<div><div class='statskill'>"+this.skill+"</div>";str+="<div class='horizontal statfire'>"+
this.weapons[0].getattack()+"</div>";str+="<div class='horizontal statevade'>"+this.getagility()+"</div>";str+="<div class='horizontal statshield'>"+this.shield+"</div>";str+="<div class='horizontal stathull'>"+this.hull+"</div></div>";str+="<div class='name'><div>"+this.name+"</div></div>";str+="<div><div style='font-size:small'><code class='"+this.faction+"'></code>"+this.ship.name+"</div></div>";str+="<div class='horizontal'><div>"+PILOTS[this.pilotid].points+"pts</div></div>";b=PILOT_translation.english[this.name+
("SCUM"==this.faction?" (Scum)":"")];"undefined"==typeof b&&(b="");str+="<div class='horizontal details'><div style='text-align:justify;margin:8px;width:100%'>"+b+"</div></div>";str+="<div class='vertical'><div>";-1<a&&(str+="<div><table style='width:100%'><tr style='width:100%'>"+this.getusabletokens(a,!1)+"</tr></table></div>");str+="</div></div>";var c=b="";a="<td class='statevade' onclick='if (!squadron["+a+"].dead) squadron["+a+"].togglerange();'>"+this.getagility()+"<span class='symbols'>^</span></td>";
b=1==this.team?b+("<tr><td></td>"+a+"</tr>"):b+("<tr>"+a+"<td></td></tr>");for(a=0;a<this.upgrades.length;a++)c+=this.upgrades[a];return str+="<table class='details' style='width:100%'>"+b+c+"</table></div>"},canusefocus:function(){return 0<this.focus},canuseevade:function(){return 0<this.evade},canusetarget:function(a){return 0<this.targeting.length&&("undefined"==typeof a||-1<this.targeting.indexOf(a))},getusabletokens:function(a,b){var c="",d="";this.canusefocus()&&(c+="<td title='"+this.focus+
" focus token(s)'"+(b?" onclick='squadron["+a+"].usefocus("+a+")'":"")+" class='xfocustoken'></td>");0<this.canuseevade()&&(c+="<td title='"+this.evade+" evade token(s)'"+(b?" onclick='squadron["+a+"].useevade("+a+")'":"")+" class='xevadetoken'></td>");for(var e=0;e<this.targeting.length;e++)d+=this.targeting[e].name+" ";0<this.canusetarget()&&(c+="<td title='targeting "+d.replace(/\'/g,"&#39;")+"'"+(b?" onclick='squadron["+a+"].usetarget()'":"")+" class='xtargettoken'></td>");d="";for(e=0;e<this.istargeted.length;e++)d+=
this.istargeted[e].name+" ";""!=d&&(c+="<td title='targeted by "+d.replace(/\'/g,"&#39;")+"' class='xtargetedtoken'></td>");this.iscloaked&&(c+="<td class='xcloaktoken'"+(b?" onclick='squadron["+a+"].usecloack("+a+")'":"")+"></td>");0<this.stress&&(c+="<td title='"+this.stress+" stress token(s)'"+(b?" onclick='squadron["+a+"].usestress("+a+")'":"")+" class='xstresstoken'></td>");0<this.ionized&&(c+="<td title='"+this.ionized+" ionization token(s)' class='xionizedtoken'></td>");return c},showstats:function(){phase==
SELECT_PHASE1||phase==SELECT_PHASE2?$("#stats"+this.id).html("<div class='PS'>"+this.skill+"</div><div class='statfire'>"+this.weapons[0].getattack()+"</div><div class='statevade'>"+this.getagility()+"</div><div class='statshield'>"+this.shield+"</div><div class='stathull'>"+this.hull+"</div>"):(this.skillbar.attr({text:repeat("u",this.skill)}),this.firebar.attr({text:repeat("u",this.weapons[0].getattack())}),this.evadebar.attr({text:repeat("u",this.getagility())}),this.hullbar.attr({text:repeat("u",
this.hull)}),this.shieldbar.attr({text:repeat("u",this.shield+this.hull)}),$("#"+this.id).html(""+this))},showpanel:function(){var a=this.g.getBBox(),b=$("#playmat").position(),c=b.left+(a.x+(this.islarge?80:40))*$("#playmat").width()/900,a=b.top+a.y*$("#playmat").height()/900;$(".phasepanel").css({left:c+10,top:a}).appendTo("body").show()},timeforaction:function(){log("TIME FOR ACTION for "+this.name+"?"+!waitingforaction.isexecuting);return!waitingforaction.isexecuting&&this==activeunit&&this.hasmoved&&
!this.actiondone&&phase==ACTIVATION_PHASE},timeformaneuver:function(){return this==activeunit&&-1<this.maneuver&&!this.hasmoved&&this.skill==skillturn},show:function(){"undefined"!=typeof this.g&&(this.g.transform(this.m),this.g.appendTo(s),this.showoutline(),this.showstats(),this.showinfo(),activeunit==this&&(this.showpanel(),this.showdial(),this.showmaneuver(),this.timeforaction()?this.showaction():$("#actiondial").empty(),phase==ACTIVATION_PHASE&&this.showactivation(),this.showattack(),0<this.hull&&
($("#"+this.id).html(""+this),$("#"+this.id).addClass("selected"))))},showhitsector:function(a,b){var c=activeunit;activeunit=this;c!=this&&(c.unselect(),this.select());if(a){for(f=0;f<this.weapons.length&&this.weapons[f].name!=b;f++);if(f!=this.weapons.length){var c=this.weapons[f].range[0],d=this.weapons[f].range[1];if(this.weapons[f].isTurret()||this.isTurret(this.weapons[f]))this.showrange(a,c,d);else{var e,f;if(1==c){for(e=c;e<=d;e++)this.sectors.push(s.path(this.getSectorString(e,this.m)).attr({fill:this.color,
stroke:this.color,opacity:.3,pointerEvents:"none"}));if("Bilaser"==this.weapons[f].type)for(e=c;e<=d;e++)this.sectors.push(s.path(this.getSectorString(e,this.m.clone().add(MR(180,0,0)))).attr({fill:this.color,stroke:this.color,opacity:.3,pointerEvents:"none"}))}else for(e=c;e<=d;e++)this.sectors.push(s.path(this.getSubSectorString(c-1,e,this.m)).attr({fill:this.color,stroke:this.color,opacity:.3,pointerEvents:"none"}))}}}else{for(e=0;e<this.sectors.length;e++)this.sectors[e].remove();for(e=0;e<this.ranges.length;e++)this.ranges[e].remove();
this.ranges=[];this.sectors=[]}},showrange:function(a,b,c){var d=activeunit;activeunit=this;d!=activeunit&&(d.unselect(),this.select());if(a)if(1==b)for(a=b;a<=c;a++)this.ranges.push(s.path(this.getRangeString(a,this.m)).attr({fill:this.color,stroke:this.color,opacity:.3,pointerEvents:"none"}));else for(a=b;a<=c;a++)this.ranges.push(s.path(this.getSubRangeString(b-1,a,this.m)).attr({fill:this.color,stroke:this.color,opacity:.3,pointerEvents:"none"}));else{for(a=0;a<this.ranges.length;a++)this.ranges[a].remove();
this.ranges=[]}},togglehitsector:function(a){this.showhitsector(0<this.sectors.length+this.ranges.length?!1:!0,a)},togglerange:function(){this.showrange(0<this.ranges.length?!1:!0,1,3)},isintersecting:function(a,b){var c,d=!1;for(c=0;c<a.length;c++)d=d||Snap.path.isPointInside(b,a[c].x,a[c].y);return d},isinsector:function(a,b,c){var d=c.getOutlinePoints(c.m),e=this.getSectorString(b,a);if(this.getoutlinerange(a,c).d!=b)return!1;if(this.isintersecting(d,e))return!0;c=c.getOutline(c.m);a=this.getSectorPoints(b,
a);if(this.isintersecting(a,c))return c.remove(),!0;c.remove();return!1},gethitsector:function(a){var b;for(b=1;3>=b;b++)if(this.isinsector(this.m,b,a))return b;return 4},isinoutline:function(a,b,c){return this.isintersecting(b.getOutlinePoints(c),a)},checkcollision:function(a){return this.collision&&this.collides==a||a.collision&&a.collides==this},resolveocollision:function(){var a,b=this.ocollision.template;-1<this.ocollision.overlap&&b++;for(a=0;a<b;a++){var c=Math.floor(7*Math.random()),c=FACE[ATTACKDICE[c]];
"hit"==c?(this.resolvehit(1),this.checkdead()):"critical"==c&&(this.resolvecritical(1),this.checkdead())}},removeshield:function(a){record(this.id,"removeshield("+a+")");this.shield-=a},resolvehit:function(a){0!=a&&(this.shield>a?this.removeshield(a):(a-=this.shield,this.removeshield(this.shield),0<a&&this.applydamage(a)),this.showstats())},resolvecritical:function(a){0!=a&&(this.shield>a?this.removeshield(a):(a-=this.shield,this.removeshield(this.shield),0<a&&this.applycritical(a)),this.showstats())},
removehull:function(a){record(this.id,"removehull("+a+")");this.hull-=a},applydamage:function(a){this.removehull(a);log(this.name+" was dealt "+a+" <p class='hit'></p>, lost "+a+" <p class='chull'></p>")},applycritical:function(a){var b=0,c;for(c=0;c<a;c++)Math.random()<7/33&&b++;log(this.name+" was dealt "+a+" <p class='critical'></p>, lost "+(b+a)+" <p class='chull'></p>");this.removehull(b+a)},gethitrange:function(a,b){return b.team==this.team||this.checkcollision(b)||0==this.weapons[a].canfire(b)?
0:this.weapons[a].getrange(b)},gethitrangeallunits:function(){var a,b,c=[[],[],[],[],[]];for(b=0;b<squadron.length;b++){var d=squadron[b];if(d!=this)for(a=0;a<this.weapons.length;a++){var e=this.gethitrange(a,d);if(0<e){for(j=0;j<c[e].length&&c[e][j].unit!=b;j++);j<c[e].length?c[e][j].wp.push(a):c[e].push({unit:b,wp:[a]})}}}return c},getrange:function(a){return this.getoutlinerange(this.m,a).d},getoutlinerange:function(a,b){var c=this.getOutlinePoints(a),d=b.getOutlinePoints(b.m),e=90001,f,g,h=!1,
l,m;for(f=0;4>f;f++)for(g=0;4>g;g++){var p=dist(d[g],c[f]);p<e&&(e=p,l=f,m=g)}if(9E4<e)return{d:4,o:!1};var p=d[m].x-c[l].x,q=d[m].y-c[l].y,u=-c[l].x*q+c[l].y*p;for(g=0;g<OBSTACLES.length;g++){var n=OBSTACLES[g].getOutlinePoints(),r=n[0].x*q-n[0].y*p+u,t=r;for(f=1;f<n.length&&!(dist(d[m],n[f])<1.2*e&&dist(c[l],n[f])<1.2*e&&(t=n[f].x*q-n[f].y*p+u,0>t*r));f++);if(0>t*r)break}g<OBSTACLES.length&&(h=!0);return 1E4>=e?{d:1,o:h}:4E4>=e?{d:2,o:h}:{d:3,o:h}},getrangeallunits:function(){var a=[[],[],[],[],
[]],b;for(b=0;b<squadron.length;b++){var c=squadron[b];c!=this&&(c=this.getrange(c),a[c].push({unit:b}))}return a}};
