var UPGRADE_TYPES={Elite:"ept",Torpedo:"torpedo",Astromech:"amd",Turret:"turret",Missile:"missile",Crew:"crew",Cannon:"cannon",Bomb:"bomb",Title:"title",Mod:"mod",System:"system",Illicit:"illicit",Salvaged:"salvaged"};function Laser(b,c,d){return new Weapon(b,{type:c,name:"Laser",isactive:!0,attack:d,range:[1,3],isprimary:!0})}
function Bomb(b,c){$.extend(this,c);b.upgrades.push(this);log("Installing bomb "+this.name);this.isactive=!0;this.unit=b;b.bombs.push(this);this.exploded=!1;void 0!=this.init&&this.init(b)}
Bomb.prototype={isWeapon:function(){return!1},isBomb:function(){return!0},toString:function(){var b,c,d="";this.isactive||(d="class='inactive'");b="<td><code class='"+this.type+" upgrades'></code></td>";c="<td class='tdstat'>"+this.name+"</td>";return 1==this.unit.team?"<tr "+d+">"+c+b+"</tr>":"<tr "+d+">"+b+c+"</tr>"},getrangeallunits:function(){var b=[[],[],[],[],[]],c;for(c=0;c<squadron.length;c++){var d=this.getrange(squadron[c]);0<d&&b[d].push({unit:c})}return b},getbomblocation:function(){return this.unit.getpathmatrix(this.unit.m.clone().add(MR(180,
0,0)),"F1")},getrange:function(b){var c=this.getOutlinePoints(this.m);b=b.getOutlinePoints(b.m);var d=90001,e,f;for(e=0;e<c.length;e++)for(f=0;4>f;f++){var g=dist(b[f],c[e]);g<d&&(d=g)}return 9E4<d?4:1E4>=d?1:4E4>=d?2:3},resolveactionmove:function(b,c){var d;this.pos=[];var e=function(c,e,h){for(d=0;d<b.length;d++)this.pos[d].remove();this.m=c;h(this,e)}.bind(this);for(d=0;d<b.length;d++)this.pos[d]=this.getOutline(b[d]).attr({fill:"rgba(80,80,80,0.7)"}),function(d){this.pos[d].hover(function(){this.pos[d].attr({stroke:this.unit.color,
strokeWidth:"4px"})}.bind(this),function(){this.pos[d].attr({strokeWidth:"0px"})}.bind(this));this.pos[d].click(function(){e(b[d],d,c)})}.call(this,d)},drop:function(b){log("["+this.unit.name+"] dropped "+this.name);this.img=s.image("png/"+this.img,-10,-8,20,16);this.isactive=!1;this.m=b;this.outline=this.getOutline(new Snap.matrix).attr({display:"block",stroke:halftone(this.unit.color),strokeWidth:2});this.g=s.group(this.outline,this.img);this.g.hover(function(){var b=this.g.getBBox(),d=$("#playmat").position(),
e=d.left+b.x*$("#playmat").width()/900,b=d.top+(b.y-20)*$("#playmat").height()/900;$(".info").css({left:e,top:b}).html(this.name).appendTo("body").show()}.bind(this),function(){$(".info").hide()}.bind(this));this.g.transform(this.m);this.g.appendTo(s);BOMBS.push(this)},getOutlinePoints:function(b){var c=transformPoint(b,{x:-10,y:-10}),d=transformPoint(b,{x:10,y:-10}),e=transformPoint(b,{x:10,y:10});b=transformPoint(b,{x:-10,y:10});return this.op=[c,d,e,b]},getOutline:function(b){b=this.getOutlinePoints(b);
b=s.path("M "+b[0].x+" "+b[0].y+" L "+b[1].x+" "+b[1].y+" "+b[2].x+" "+b[2].y+" "+b[3].x+" "+b[3].y+" Z");b.appendTo(s);return b},explode:function(){this.exploded=!0;log("["+this.name+"] exploded");SOUNDS[this.snd].play();this.g.remove()}};function Weapon(b,c){this.isprimary=!1;$.extend(this,c);b.upgrades.push(this);log("Installing weapon "+this.name+" ["+this.type+"]");this.isactive=!0;this.unit=b;b.weapons.push(this);void 0!=this.init&&this.init(b)}
Weapon.prototype={isBomb:function(){return!1},isWeapon:function(){return!0},toString:function(){var b,c,d="";if(this.isactive){c=this.getrangeallunits();for(b=0;b<c.length&&c[b].team==this.unit.team;b++);b==c.length&&(d="class='nofire'")}else d="class='inactive'";for(b=0;b<squadron.length&&squadron[b]!=this.unit;b++);b="<td class='statfire'"+(" onclick='if (!squadron["+b+"].dead) squadron["+b+'].togglehitsector("'+this.name.replace(/\'/g,"&#39;")+"\")'");b+=">"+this.getattack()+"<span class='symbols'>"+
A[this.type.toUpperCase()].key+"</span></td>";c="<td class='tdstat'>"+this.name.replace(/\'/g,"&#39;")+" <span style='font-size:x-small'>";"undefined"!=typeof this.getrequirements()&&("Target".match(this.getrequirements())&&(c+="<code class='symbols'>"+A.TARGET.key+"</code>"),"Focus".match(this.getrequirements())&&(c+=(5<this.getrequirements().length?"/":"")+"<code class='symbols'>"+A.FOCUS.key+"</code>"));c+="["+this.range[0]+"-"+this.range[1]+"]</span></td>";return 1==this.unit.team?"<tr "+d+">"+
c+b+"</tr>":"<tr "+d+">"+b+c+"</tr>"},getrequirements:function(){return this.requires},getattack:function(){return this.attack},isTurret:function(){return"Turret"==this.type},isinrange:function(b){return b>=this.range[0]&&b<=this.range[1]},modifydamagegiven:function(b){return b},modifydamageassigned:function(b,c){return b},canfire:function(b){return!this.isactive||this.unit.checkcollision(b)?!1:"undefined"!=typeof this.getrequirements()?"Target".match(this.getrequirements())&&this.unit.canusetarget(b)?
!0:"Focus".match(this.getrequirements())&&this.unit.canusefocus(b)?!0:!1:!0},getattackreroll:function(b){return 0},modifyattackroll:function(b,c){return b},getattackbonus:function(b){return this.isprimary&&1==this.getrange(b)?(log(this.unit.name+" +1 attack for range 1"),1):0},declareattack:function(b){"undefined"!=typeof this.getrequirements()&&("Target".match(this.getrequirements())&&this.unit.canusetarget(b)?this.unit.removetarget(b):"Focus".match(this.getrequirements())&&this.unit.canusefocus(b)&&
this.unit.removefocustoken(),this.unit.show())},getdefensebonus:function(b){return this.isprimary&&3==this.getrange(b)?(log(b.name+" +1 defense for range 3 against "+this.unit.name),1):0},getrange:function(b){var c;if(!this.canfire(b))return 0;if(this.isTurret()||this.unit.isTurret(this))return b=this.unit.getrange(b),this.isinrange(b)?b:0;for(c=this.range[0];c<=this.range[1];c++)if(this.unit.isinsector(this.unit.m,c,b))return c;if("Bilaser"==this.type){var d=this.unit.m.clone();d.add(MR(180,0,0));
for(c=this.range[0];c<=this.range[1];c++)if(this.unit.isinsector(d,c,b)&&log(b.name+" in range "+c),this.unit.isinsector(d,c,b))return c}return 0},endattack:function(b,c){this.type.match("Torpedo|Missile")&&(this.isactive=!1,log("["+this.name.replace(/\'/g,"&#39;")+"] inactive"))},getrangeallunits:function(){var b,c=[];for(b=0;b<squadron.length;b++){var d=squadron[b];0<this.getrange(d)&&c.push(d)}return c}};
function Upgrade(b,c){$.extend(this,UPGRADES[c]);b.upgrades.push(this);log("Installing upgrade "+this.name.replace(/\'/g,"&#39;")+" ["+this.type+"]");this.isactive=!0;this.unit=b;void 0!=this.init&&this.init(b)}
function Upgradefromname(b,c){var d;for(d=0;d<UPGRADES.length;d++)if(UPGRADES[d].name==c){var e=UPGRADES[d];return"Bomb"==e.type?new Bomb(b,e):"undefined"!=typeof e.isWeapon?e.isWeapon()?new Weapon(b,e):new Upgrade(b,d):e.type.match("Turretlaser|Bilaser|Laser|Torpedo|Cannon|Missile|Turret")||1==e.isweapon?new Weapon(b,e):new Upgrade(b,d)}console.log("Could not find upgrade "+c)}
Upgrade.prototype={toString:function(){var b,c,d="";this.isactive||(d="class='inactive'");b="<td><code class='"+this.type+" upgrades'></code></td>";c="<td class='tdstat'>"+this.name.replace(/\'/g,"&#39;")+"</td>";return 1==this.unit.team?"<tr "+d+">"+c+b+"</tr>":"<tr "+d+">"+b+c+"</tr>"},isWeapon:function(){return!1},isBomb:function(){return!1}};
var rebelonly=function(b){var c;for(c=0;c<PILOTS.length;c++)if(b==PILOTS[c].name&&"REBEL"==PILOTS[c].faction)return!0;return!1},empireonly=function(b){var c;for(c=0;c<PILOTS.length;c++)if(b==PILOTS[c].name&&"EMPIRE"==PILOTS[c].faction)return!0;return!1},UPGRADES=[{name:"Ion Cannon Turret",type:"Turret",firesnd:"falcon_fire",points:5,attack:3,done:!0,modifydamageassigned:function(b,c){0<b&&(b=1,log("["+this.name+"] 1<p class='hit'></p> + 1 ion token assigned to "+c.name),c.addiontoken());return b},
range:[1,2]},{name:"Proton Torpedoes",requires:"Target",type:"Torpedo",firesnd:"missile",points:4,done:!0,attack:4,init:function(b){b.addattackmoda(this,function(c,d){return b.weapons[b.activeweapon]==this?!0:!1}.bind(this),function(b,d){return 0<Math.floor(b/100)%10?(log("[Proton Torpedoes] 1 <p class='focus'></p> -> 1 <p class='critical'></p>"),b-90):b}.bind(this),!1,"focus")},range:[2,3]},{name:"R2 Astromech",done:!0,install:function(b){b.gdr2=b.getdial;b.getdial=function(){for(var c=b.gdr2(),
d=[],e=0;e<c.length;e++){var f=P[c[e].move].speed,g=c[e].difficulty;if(1==f||2==f)g="GREEN";d.push({move:c[e].move,difficulty:g})}return d}.bind(b);log("["+this.name+"] 1, 2 speed maneuvers of "+b.name+" are green")},uninstall:function(b){b.getdial=b.gdr2;log("["+this.name+"] uninstalling effect")},type:"Astromech",points:1},{name:"R2-D2",done:!0,init:function(b){var c=b.handledifficulty;b.handledifficulty=function(b){c.call(this,b);"GREEN"==b&&this.shield<this.ship.shield&&(this.shield++,log("[R2-D2] "+
this.name+" recovers 1 shield"))}},unique:!0,type:"Astromech",points:4},{name:"R2-F2",done:!0,candoaction:function(){return!0},action:function(){var b=this.unit.getagility,c=this.unit.endround;log("[R2-F2] +1 agility for "+this.unit.name+" until end of round");this.unit.getagility=function(){return b.call(this)+1};this.unit.endround=function(){this.unit.getagility=b;this.unit.endround=c;c.call(this)};this.unit.showstats();this.endaction();return!0},unique:!0,type:"Astromech",points:3},{name:"R5-D8",
unique:!0,type:"Astromech",points:3},{name:"R5-K6",init:function(b){var c=b.removetarget;b.removetarget=function(b){c.call(this,b);var e=Math.floor(7*Math.random());"evade"==FACE[DEFENSEDICE[e]]&&(this.addtarget(b),log("[R5-K6] target lock on "+b.name),record(this.id,"TT"+b.id))}},done:!0,unique:!0,type:"Astromech",points:2},{name:"R5 Astromech",type:"Astromech",points:1},{name:"Determination",type:"Elite",points:1},{name:"Swarm Tactics",type:"Elite",points:2,done:!0,init:function(b){b.begincombatphase=
function(){b.dead||waitingforaction.add(function(){var c=b.selectnearbyunits(1,function(b,c){return b.team==c.team&&b!=c});0<c.length?(log("<b>["+this.name+"] sets a pilot skill to the skill of "+b.name+"</b>"),b.resolveactionselection(c,function(d){log(c[d].name+" has "+b.skill+" pilot skill");c[d].oldskill=c[d].skill;log("old skill :"+c[d].oldskill);c[d].skill=b.skill;filltabskill();c[d].show();var e=c[d].endcombatphase;c[d].endcombatphase=function(){e.call(this);this.skill=this.oldskill;log(this.name+
" has "+this.skill+" pilot skill");squadron.sort(function(b,c){return c.skill-b.skill});filltabskill();this.show()}.bind(c[d]);nextstep()}.bind(b))):nextstep()}.bind(this))}}},{name:"Squad Leader",unique:!0,done:!0,type:"Elite",points:2,candoaction:function(){this.p=this.unit.selectnearbyunits(2,function(b,c){return b.team==c.team&&c!=b&&c.skill<b.skill});return 0<this.p.length},action:function(){var b=this.unit;this.unit.resolveactionselection(p,function(c){p[c].freeaction(function(){b.endaction()})})}},
{name:"Expert Handling",candoaction:function(){return!0},action:function(){-1==this.unit.shipactionList.indexOf("ROLL")&&this.unit.addstress();this.unit.resolveroll();0<this.unit.istargeted.length&&waitingforaction.add(function(){log("<b>["+this.name+"] remove 1 target lock from "+this.unit.name+"</b>");this.unit.resolveactionselection(this.unit.istargeted,function(b){this.istargeted[b].removetarget(this);nextstep()}.bind(this.unit))}.bind(this))},type:"Elite",done:!0,points:2},{name:"Marksmanship",
candoaction:function(){return!0},action:function(){this.unit.addattackmoda(this,function(b,c){return!0}.bind(this.unit),function(b,c){var d=Math.floor(b/100);log("[Marksmanship] "+d+" <code class='xfocustoken'></code> -> 1 <code class='critical'></code>"+(1<d?"+ "+(d-1)+"<code class='hit'></code>":""));return 1<d?b-100*d+10+(d-1):b-90},!1,"focus");this.unit.endaction()},done:!0,type:"Elite",points:3},{name:"Concussion Missiles",requires:"Target",type:"Missile",firesnd:"missile",points:4,attack:4,
range:[2,3]},{name:"Cluster Missiles",type:"Missile",firesnd:"missile",requires:"Target",points:4,attack:3,range:[1,2]},{name:"Daredevil",done:!0,candoaction:function(){return!0},action:function(){log("<b>["+this.name+"] select maneuver to perform</b>");this.unit.resolveactionmove([this.unit.getpathmatrix(this.unit.m.clone(),"TL1"),this.unit.getpathmatrix(this.unit.m.clone(),"TR1")],function(b){b.addstress();if(-1==b.shipactionList.indexOf("BOOST")){log("[Daredevil] "+b.name+" no boost -> 2 rolls for damage");
for(var c=0;2>c;c++){var d=Math.floor(7*Math.random()),d=FACE[ATTACKDICE[d]];"hit"==d?(b.resolvehit(1),b.checkdead()):"critical"==d&&(b.resolvecritical(1),b.checkdead())}}b.endaction()},!0)},type:"Elite",points:3},{name:"Elusiveness",type:"Elite",points:2},{name:"Homing Missiles",requires:"Target",type:"Missile",firesnd:"missile",attack:4,range:[2,3],done:!0,init:function(b){var c=b.resolveattack,d=this;b.resolveattack=function(b,e){this.weapons[b]==d&&(this.cufhm=e.canusefocus,log("[Homing Missile] "+
e.name+" cannot use focus"),e.canusefocus=function(){return!1});c.call(this,b,e)};var e=this.endattack;this.endattack=function(b,c){e.call(this,b,c);targetunit.canusefocus=this.unit.cufhm}},points:5},{name:"Push the Limit",init:function(b){var c=b.endaction;b.r=-1;b.endaction=function(){this.r!=round&&(this.r=round,waitingforaction.add(function(){log("[Push the Limit] select an action or empty to cancel");this.freeaction(function(){log("endfree action with action="+this.action);-1<this.action?(this.r=
round,this.addstress()):this.r=-1;nextstep()}.bind(this))}.bind(this)));c.call(this)}},done:!0,type:"Elite",points:3},{name:"Deadeye",init:function(b){var c=Weapon.prototype.getrequirements;Weapon.prototype.getrequirements=function(){var d=c.call(this);return this.unit==b&&"Target"==d?"Target|Focus":d}},done:!0,type:"Elite",points:1},{name:"Expose",candoaction:function(){return!0},action:function(){var b=this.unit.getagility,c=this.unit.weapons[0],d=c.getattack,e=this.unit.endround;log("["+this.name+
"] -1 agility, +1 primary attack until end of turn");this.unit.getagility=function(){var c=b.call(this)-1;return 0<=c?c:0};c.getattack=function(){return d.call(c)+1};this.unit.endround=function(){this.getagility=b;c.getattack=d;this.endround=e};this.unit.showstats();this.unit.endaction()},done:!0,type:"Elite",points:4},{name:"Gunner",done:!0,init:function(b){var c=b.endattack;b.endattack=function(b,e){c.call(this,b,e);0==b+e&&2>this.hasfired&&(log("[Gunner] "+this.name+" attacks again with primary weapon"),
this.selecttargetforattack(0))}},type:"Crew",points:5},{name:"Ion Cannon",type:"Cannon",firesnd:"slave_fire",done:!0,modifydamageassigned:function(b,c){0<b&&(b=1,log("["+this.name+"] 1<p class='hit'></p> + 1 ion token assigned to "+c.name),c.addiontoken());return b},points:3,attack:3,range:[1,3]},{name:"Heavy Laser Cannon",type:"Cannon",firesnd:"slave_fire",done:!0,modifydamagegiven:function(b){if(10<b){var c=Math.floor(b/10);b-=10*c;log("["+this.name+"] "+c+"<p class='critical'></p>-> "+c+"<p class='hit'></p>");
b=c+b}return b},points:7,attack:4,range:[2,3]},{name:"Seismic Charges",done:!0,img:"seismic.png",snd:"explode",explode:function(){if(phase==ACTIVATION_PHASE&&!this.exploded){var b=this.getrangeallunits(),c;for(c=0;c<b[1].length;c++)squadron[b[1][c].unit].resolvehit(1);BOMBS.splice(BOMBS.indexOf(this),1);Bomb.prototype.explode.call(this)}},type:"Bomb",points:2},{name:"Mercenary Copilot",type:"Crew",points:2},{name:"Assault Missiles",type:"Missile",requires:"Target",firesnd:"missile",done:!0,modifydamageassigned:function(b,
c){if(0<b){log("["+this.name+"] 1 damage assigned to all units at range 1 of "+c.name);for(var d=c.getrangeallunits(),e=0;e<d[1].length;e++)squadron[d[1][e].unit].resolvehit(1)}return b},points:5,attack:4,range:[2,3]},{name:"Veteran Instincts",done:!0,install:function(b){b.skill+=2},uninstall:function(b){b.skill-=2},type:"Elite",points:1},{name:"Proximity Mines",type:"Bomb",points:3},{name:"Weapons Engineer",type:"Crew",points:3},{name:"Draw Their Fire",type:"Elite",points:1},{name:"Luke Skywalker",
faction:"REBEL",unique:!0,done:!0,init:function(b){var c=b.endattack;b.endattack=function(b,e){c.call(this,b,e);0==b+e&&2>this.hasfired&&(log("[Luke Skywalker] "+this.name+" attacks again with primary weapon"),this.selecttargetforattack(0))};b.addattackmoda(this,function(b,c){return 2==this.hasfired?!0:!1}.bind(b),function(b,c){return 100<b?b-99:b},!1,"focus")},type:"Crew",points:7},{name:"Nien Nunb",faction:"REBEL",done:!0,install:function(b){b.getdial=function(){for(var b=Unit.prototype.getdial.call(this),
d=[],e=0;e<b.length;e++){var f=b[e].move,g=b[e].difficulty;f.match("F1|F2|F3|F4|F5")&&(g="GREEN");d.push({move:f,difficulty:g})}return d}.bind(b)},uninstall:function(b){b.getdial=Unit.prototype.getdial},unique:!0,type:"Crew",points:1},{name:"Chewbacca",faction:"REBEL",unique:!0,type:"Crew",points:4},{name:"Advanced Proton Torpedoes",requires:"Target",type:"Torpedo",firesnd:"missile",attack:5,done:!0,range:[1,1],init:function(b){b.addattackmoda(this,function(c,d){return b.weapons[b.activeweapon]==
this?!0:!1}.bind(this),function(b,d){var e=b%10+Math.floor(b/10)%10+Math.floor(b/100)%10;0<d-e&&(log("[Advanced Proton Torpedoes] change "+(d-e)+" blanks by focus"),b=3>d-e?b+100*(d-e):b+300);return b}.bind(this),!1,"blank")},points:6},{name:"Autoblaster",type:"Cannon",done:!0,firesnd:"slave_fire",attack:3,init:function(b){var c=Unit.prototype.cancelhit;Unit.prototype.cancelhit=function(b,e,f){return"Autoblaster Turret"==f.weapons[f.activeweapon].name?(log("[Autoblaster Turret] Hits cannot be cancelled by defense dice"),
b):c.call(this,b,e,f)}},range:[1,1],points:5},{name:"Fire-Control System",done:!0,init:function(b){var c=b.cleanupattack;b.cleanupattack=function(){log("[Fire-Control System] free target lock on "+targetunit.name);this.addtarget(targetunit);c.call(this)}.bind(b)},type:"System",points:2},{name:"Blaster Turret",type:"Turret",done:!0,firesnd:"falcon_fire",requires:"Focus",points:4,attack:3,range:[1,2]},{name:"Recon Specialist",init:function(b){b.addfocus=function(){b.addfocustoken();return Unit.prototype.addfocus.call(this)}},
done:!0,type:"Crew",points:3},{name:"Saboteur",type:"Crew",points:2},{name:"Intelligence Agent",type:"Crew",points:1},{name:"Proton Bombs",done:!0,snd:"explode",img:"proton.png",explode:function(){if(phase==ACTIVATION_PHASE&&!this.exploded){var b=this.getrangeallunits(),c;for(c=0;c<b[1].length;c++)squadron[b[1][c].unit].applycritical(1);BOMBS.splice(BOMBS.indexOf(this),1);Bomb.prototype.explode.call(this)}},type:"Bomb",points:5},{name:"Adrenaline Rush",type:"Elite",points:1},{name:"Advanced Sensors",
done:!0,init:function(b){var c=b.timeforaction;b.timeforaction=function(){this.isactive||(this.timeforaction=c);log("[Advanced Sensors] action before maneuver for "+this.name);return this==activeunit&&!this.actiondone&&phase==ACTIVATION_PHASE}},type:"System",points:3},{name:"Sensor Jammer",type:"System",points:4},{name:"Darth Vader",faction:"EMPIRE",unique:!0,type:"Crew",points:3},{name:"Rebel Captive",faction:"EMPIRE",done:!0,init:function(b){var c=b.ishit;b.rebelcaptive=0;b.ishit=function(b){this.rebelcaptive!=
round&&(log("[Rebel Captive] +1 stress for "+b.name),b.addstress(),this.rebelcaptive=round);return c.call(this,b)}.bind(b)},unique:!0,type:"Crew",points:3},{name:"Flight Instructor",init:function(b){b.adddefensererolld(this,["focus"],function(){return 2>=activeunit.skill?2:1},function(b,d){log("[Flight Instructor] +"+(2>=activeunit.skill?2:1)+" reroll(s)");return!0},!1)},done:!0,type:"Crew",points:4},{name:"Navigator",init:function(b){var c=b.completemaneuver;b.completemaneuver=function(b,e,f){var g=
e.replace(/\d/,""),h=this.getdial(),k=[],l=[];l.push(e);k.push(this.getpathmatrix(this.m.clone(),e));for(i=0;i<h.length;i++)!h[i].move.match(g)||h[i].move==e||h[i].difficulty==RED&&0!=this.stress||(k.push(this.getpathmatrix(this.m.clone(),h[i].move)),l.push(h[i].move));1<k.length?(log("<b>[Navigator] choose maneuver of bearing "+g+"</b>"),this.resolveactionmove(k,function(b,d){c.call(b,l[d],l[d],f)},!1,!0)):c.call(this,b,e,f)}},done:!0,type:"Crew",points:3},{name:"Opportunist",done:!0,init:function(b){var c=
b.getattackstrength;b.getattackstrength=function(b,e){var f=c.call(this,b,e);0==e.focus+e.evade&&(f+=1,this.addstress(),log("[Opportunist] +1 attack against "+e.name+", 1 stress more"));return f}},type:"Elite",points:4},{name:"Ion Pulse Missiles",requires:"Target",type:"Missile",firesnd:"missile",done:!0,modifydamageassigned:function(b,c){0<b&&(log("["+this.name+"] 2<p class='hit'></p> + 1 ion token assigned by "+c.name),b=2,c.ionized+=2);return b},points:3,attack:3,range:[2,3]},{name:"Wingman",done:!0,
init:function(b){var c=b.begincombatphase;b.begincombatphase=function(){this.dead||(c.call(this),waitingforaction.add(function(){var b=this.selectnearbyunits(1,function(b,c){return b.team==c.team&&b!=c&&0<c.stress});0<b.length?(log("<b>[Wingman] select a pilot with stress to remove.</b>"),this.resolveactionselection(b,function(c){b[c].removestresstoken();nextstep()})):nextstep()}.bind(this)))}},type:"Elite",points:2},{name:"Decoy",init:function(b){b.begincombatphase=function(){this.dead||waitingforaction.add(function(){var b=
this.selectnearbyunits(2,function(b,c){return b.team==c.team&&b!=c});b.push(this);1<b.length?(log("<b>[Decoy] select a pilot skill to exchange with "+this.name+" (or self to cancel)</b>"),this.resolveactionselection(b,function(d){if(b[d]!=this){var e=this.skill;this.skill=b[d].skill;b[d].skill=e;filltabskill();b[d].show();this.show()}nextstep()}.bind(this))):nextstep()}.bind(this))}},done:!0,type:"Elite",points:2},{name:"Outmaneuver",done:!0,init:function(b){b.raoutmaneuver=b.resolveattack;b.resolveattack=
function(c,d){d.tagility=d.agility;this.isinsector(this.m,3,d)&&!d.isinsector(d.m,3,b)&&(log("[Outmaneuver] -1 agility for "+d.name),d.agility--);this.raoutmaneuver.call(this,c,d)}.bind(b);b.eaoutmaneuver=b.endattack;b.endattack=function(b,d){targetunit.agility=targetunit.tagility;this.eaoutmaneuver.call(this,b,d)}.bind(b)},type:"Elite",points:3},{name:"Predator",done:!0,init:function(b){b.addattackrerolla(this,["blank","focus"],function(){return 2>=targetunit.skill?2:1},function(b,d){log("[Predator] "+
(2>=targetunit.skill?2:1)+" reroll(s)");return!0},!1)},type:"Elite",points:3},{name:"Flechette Torpedoes",requires:"Target",type:"Torpedo",firesnd:"missile",done:!0,endattack:function(b,c){4>=targetunit.hull&&targetunit.addstress();this.isactive=!1},points:2,attack:3,range:[2,3]},{name:"R7 Astromech",type:"Astromech",points:2},{name:"R7-T1",candoaction:function(){return!0},action:function(){var b=this.unit.selectnearbyunits(2,function(b,d){return b.team!=d.team});0<b.length?(b.push(this.unit),log("<b>[R7-T1] acquire target lock on target enemy ship (self to ignore)</b>"),
this.unit.resolveactionselection(b,function(c){b[c]!=this?(3>=b[c].gethitsector(this)&&this.addtarget(b[c]),this.resolveboost()):this.endaction()})):this.unit.endaction()},done:!0,unique:!0,type:"Astromech",points:3},{name:"Tactician",type:"Crew",points:2,done:!0,init:function(b){var c=b.endattack;b.endattack=function(b,e){c.call(this);this.isinsector(this.m,2,targetunit)&&(targetunit.addstress(),log("[Tactician] +1 stress for "+targetunit.name))}.bind(b)}},{name:"R2-D2",faction:"REBEL",unique:!0,
type:"Crew",points:4},{name:"C-3PO",unique:!0,faction:"REBEL",type:"Crew",points:3},{name:"R3-A2",done:!0,init:function(b){var c=b.declareattack;b.declareattack=function(b,e){c.call(this,b,e);this.isinsector(this.m,3,e)&&(this.addstress(),log("[R3-A2] +1 stress for "+e.name+" and "+this.name),e.addstress())}},unique:!0,type:"Astromech",points:2},{name:"R2-D6",upgrades:["Elite"],noupgrades:"Elite",skillmin:3,done:!0,unique:!0,type:"Astromech",points:1},{name:"Enhanced Scopes",done:!0,init:function(b){b.beginactivationphase=
function(){b.oldskill=b.skill;log("[Enhanced Scopes] "+b.name+" skill set to 0");b.skill=0};b.endactivationphase=function(){b.skill=b.oldskill}},type:"System",points:1},{name:"Chardaan Refit",type:"Missile",done:!0,isWeapon:function(){return!1},points:-2,ship:"A-Wing"},{name:"Proton Rockets",type:"Missile",firesnd:"missile",requires:"Focus",points:3,attack:2,done:!0,getattack:function(){a=this.attack;a=3>=this.unit.agility?a+this.unit.agility:a+3;log("[Proton Rockets] +"+(3<this.unit.agility?3:this.unit.agility)+
" attack for agility");return a},range:[1,1]},{name:"Kyle Katarn",faction:"REBEL",unique:!0,done:!0,type:"Crew",points:3,init:function(b){var c=b.removestresstoken;b.removestresstoken=function(){c.call(this);this.addfocustoken()}.bind(b)}},{name:"Jan Ors",faction:"REBEL",unique:!0,type:"Crew",points:2},{name:"R4-D6",init:function(b){var c=b.cancelhit;b.cancelhit=function(d,e,f){d=c.call(this,d,e,f);if(3<=d)for(d-=2,e=0;e<d;e++)b.addstress();return d}},done:!0,unique:!0,type:"Astromech",points:1},
{name:"R5-P9",done:!0,init:function(b){var c=b.endcombatphase;b.endcombatphase=function(){c.call(this);this.shield<this.ship.shield&&this.canusefocus()&&(this.shield++,log("[R5-P9] 1 <code class='xfocustoken'></code> -> 1 <code class='cshield'></code>"),this.removefocustoken())}.bind(b)},unique:!0,type:"Astromech",points:3},{name:"Han Solo",faction:"REBEL",type:"Crew",unique:!0,points:2},{name:"Leia Organa",faction:"REBEL",type:"Crew",unique:!0,points:4},{name:"Targeting Coordinator",type:"Crew",
limited:!0,points:4},{name:"Lando Calrissian",faction:"REBEL",type:"Crew",unique:!0,points:3},{name:"Mara Jade",faction:"EMPIRE",type:"Crew",unique:!0,done:!0,init:function(b){b.endcombatphase=function(){var b=this.gettargetableunits(1),d;0<b.length&&log("[Mara Jade] +1 stress for all enemies in range 1");for(d=0;d<b.length;d++)0==b[d].stress&&b[d].addstress()}.bind(b)},points:3},{name:"Fleet Officer",faction:"EMPIRE",type:"Crew",points:3},{name:"Stay On Target",type:"Elite",points:2,done:!0,init:function(b){var c=
b.completemaneuver;b.completemaneuver=function(b,e,f){var g=e.substr(-1),h=this.getdial(),k=[],l=[];l.push(e);k.push(this.getpathmatrix(this.m.clone(),e));for(i=0;i<h.length;i++)h[i].move.substr(-1)==g&&h[i].move!=e&&(k.push(this.getpathmatrix(this.m.clone(),h[i].move)),l.push(h[i].move));1<k.length?(log("<b>[Stay on target] choose maneuver of speed "+g+"</b>"),this.resolveactionmove(k,function(b,d){c.call(b,l[d],l[d],0==d?f:RED)},!1,!0)):c.call(this,b,e,f)}}},{name:"Dash Rendar",faction:"REBEL",
unique:!0,type:"Crew",points:2},{name:"Lone Wolf",done:!0,init:function(b){b.addattackrerolla(this,["blank"],function(){return 1},function(b,d){this.unit.getrangeallunits();for(var e=0;e<squadron.length;e++)if(2>=squadron[e].getrange(this.unit)&&squadron[e].team==this.unit.team)return!1;log("[Lone Wolf] 1 reroll");return!0},!1)},unique:!0,type:"Elite",points:2},{name:"'Leebo'",faction:"REBEL",unique:!0,candoaction:function(){return!0},action:function(){log("["+this.name+"] free boost and ion token");
this.unit.addiontoken();this.unit.resolveboost()},done:!0,type:"Crew",points:2},{name:"Ruthlessness",faction:"EMPIRE",type:"Elite",points:3,done:!0,init:function(b){var c=b.endattack;b.endattack=function(b,e){c.call(this);var f=targetunit.selectnearbyunits(1,function(b,c){return!0});0<f.length&&this.resolveactionselection(f,function(b){log("[Ruthlessness] +1 hit to "+f[b].name);f[b].resolvehit(1);f[b].checkdead()})}.bind(b)}},{name:"Intimidation",done:!0,init:function(b){var c=this;c.ga=b.getagility;
b.getagility=function(){var b=c.ga.call(this);return this.team!=c.team&&0<b&&this.iscollidingunit(this.m,c)?(log("[Intimidation] -1 agility to "+this.name),b-1):b}},type:"Elite",points:2},{name:"Ysanne Isard",faction:"EMPIRE",unique:!0,done:!0,init:function(b){b.bcpisard=b.begincombatphase;b.begincombatphase=function(){this.bcpisard.call(this);0==this.shield&&this.hull<this.ship.hull&&this.candoevade()&&(this.addevadetoken(),log("[Ysanne Isard] +1 free evade"))}.bind(b)},done:!0,type:"Crew",points:4},
{name:"Moff Jerjerrod",faction:"EMPIRE",unique:!0,type:"Crew",points:2},{name:"Ion Torpedoes",requires:"Target",type:"Torpedo",firesnd:"missile",done:!0,modifydamageassigned:function(b,c){if(0<b){log("["+this.name+"] 1 ion token for all units at range 1 of "+c.name);c.addiontoken();for(var d=c.getrangeallunits(),e=0;e<d[1].length;e++)squadron[d[1][e].unit].addiontoken()}return b},points:5,attack:4,range:[2,3]},{name:"Bodyguard",faction:"SCUM",unique:!0,done:!0,init:function(b){var c=b.begincombatphase;
b.begincombatphase=function(){c.call(this);this.dead||waitingforaction.add(function(){var b=this.selectnearbyunits(1,function(b,c){return b.team==c.team&&b!=c&&b.skill<c.skill});b.push(this);1<b.length&&this.canusefocus()?(log("<b>["+this.name+"] increase agility of selected pilot</b>"),this.resolveactionselection(b,function(c){if(this!=b[c]){b[c].agility++;this.removefocustoken();this.show();var f=b[c].endcombatphase;b[c].endcombatphase=function(){f.call(this);this.agility--;this.showstats();b[c].endcombatphase=
f}.bind(b[c])}nextstep()}.bind(this))):nextstep()}.bind(b))}},type:"Elite",points:2},{name:"Calculation",done:!0,init:function(b){b.addattackmoda(this,function(b,d){return this.canusefocus()}.bind(b),function(b,d){return 0<Math.floor(b/100)%10?(log("[Calculation] 1 <p class='focus'></p> -> 1 <p class='critical'></p>"),b-90):b},!1,"focus")},type:"Elite",points:1},{name:"Accuracy Corrector",init:function(b){b.addattackmoda(this,function(b,d){return!0}.bind(this),function(b,d){log("[Accuracy Corrector] replace all dice by 2 <p class='hit'></p>");
return 2}.bind(this),!1,"blank")},done:!0,type:"System",points:3},{name:"Inertial Dampeners",done:!0,init:function(b){var c=b.updateactivationdial,d=this;b.updateactivationdial=function(){var b=c.call(this);this.addactivationdial(function(){return!d.unit.hasmoved&&d.isactive},function(){d.unit.completemaneuver("F0","F0","WHITE");d.isactive=!1;d.unit.addstress()},A.ILLICIT.key,$("<div>").attr({class:"symbols"}));return b}},type:"Illicit",points:1},{name:"Flechette Cannon",type:"Cannon",firesnd:"slave_fire",
done:!0,modifydamageassigned:function(b,c){0<b&&(b=1,log("["+this.name+"] 1<p class='hit'></p> and stress token for "+c.name),0==c.stress&&c.addstress());return b},points:2,attack:3,range:[1,3]},{name:"'Mangler' Cannon",type:"Cannon",firesnd:"slave_fire",points:4,attack:3,done:!0,modifydamagegiven:function(b){0<b%10&&(log("["+this.name+"] 1<p class='hit'></p>-> 1 <p class='critical'></p>"),b+=9);return b},range:[1,3]},{name:"Dead Man's Switch",done:!0,init:function(b){var c=b.dies;b.dies=function(){var d,
e=b.getrangeallunits();c.call(this);log("[Dead Man's Switch] 1 damage for all units in range 1");for(d=0;d<e[1].length;d++)squadron[e[1][d].unit].applydamage(1)}},type:"Illicit",points:2},{name:"Feedback Array",type:"Illicit",points:2},{name:"'Hot Shot' Blaster",done:!0,isWeapon:function(){return!0},isTurret:function(){return!0},endattack:function(b,c){this.isactive=!1},type:"Illicit",firesnd:"xwing_fire",points:3,attack:3,range:[1,2]},{name:"Greedo",faction:"SCUM",unique:!0,type:"Crew",points:1},
{name:"Salvaged Astromech",type:"Salvaged",points:2},{name:"Bomb Loadout",upgrades:["Bomb"],done:!0,isWeapon:function(){return!1},limited:!0,type:"Torpedo",points:0,ship:"Y-Wing"},{name:"'Genius'",unique:!0,done:!0,init:function(b){b.candropbomb=function(){return phase==ACTIVATION_PHASE}},type:"Salvaged",points:0},{name:"Unhinged Astromech",type:"Salvaged",done:!0,install:function(b){var c;b.gd=b.getdial;b.getdial=function(){var d=b.gd(),e=[];for(c=0;c<d.length;c++){var f=d[c].difficulty,g=d[c].move;
g.match("F3|TL3|TR3|BL3|BR3|SR3|SR3|K3")&&(f="GREEN");e.push({move:g,difficulty:f})}return e}},uninstall:function(b){b.getdial=b.gd},points:1},{name:"R4-B11",unique:!0,type:"Salvaged",points:3},{name:"Autoblaster Turret",type:"Turret",firesnd:"falcon_fire",done:!0,points:2,attack:2,init:function(b){var c=Unit.prototype.cancelhit;Unit.prototype.cancelhit=function(b,e,f){return"Autoblaster Turret"==f.weapons[f.activeweapon].name?(log("[Autoblaster Turret] Hits cannot be cancelled by defense dice"),
b):c.call(this,b,e,f)}},range:[1,1]},{name:"R4 Agromech",done:!0,init:function(b){b.usefocusattack=function(b){0==this.target&&(log("[R4 Agromech] free target lock"),this.addtarget(targetunit));Unit.prototype.usefocusattack.call(this,b)};b.declareattack=function(b,d){var e=this.weapons[b].getrequirements();"undefined"!=typeof e&&"Focus".match(e)&&this.canusefocus(d)&&(log("[R4 Agromech] free target lock"),this.addtarget(d));Unit.prototype.declareattack.call(this,b,d)}},type:"Salvaged",points:2},{name:"K4 Security Droid",
faction:"SCUM",type:"Crew",done:!0,init:function(b){b.handledifficulty=function(b){Unit.prototype.handledifficulty.call(this,b);"GREEN"==b&&waitingforaction.add(function(){var b=this.gettargetableunits(3);0<b.length?(b.push(this),log("[K4 Security Droid] select unit to target lock for "+this.name+" (self to cancel)"),this.resolveactionselection(b,function(c){this!=b[c]&&(this.addtarget(b[c]),log("["+this.name+"] lock target "+b[c].name));nextstep()}.bind(this))):nextstep()}.bind(this))}},points:3},
{name:"Outlaw Tech",faction:"SCUM",limited:!0,done:!0,type:"Crew",init:function(b){b.handledifficulty=function(c){Unit.prototype.handledifficulty(c);"RED"==c&&b.addfocustoken()}},points:2},{name:"Advanced Targeting Computer",type:"System",points:5,ship:"TIE Advanced"},{name:"Stealth Device",type:"Mod",done:!0,install:function(b){b.agility++},uninstall:function(b){b.agility--},init:function(b){log("["+this.name+"] +1 agility for "+b.name);var c=b.ishit;b.ishit=function(b){var e;for(e=0;e<this.upgrades.length&&
"Stealth Device"!=this.upgrades[e].name;e++);this.upgrades[e].isactive&&(this.upgrades[e].isactive=!1,this.agility--,log("["+this.name+"] "+this.upgrades[e].name+" is hit => equipment destroyed"),this.show());c.call(this,b)}.bind(b)},points:3},{name:"Shield Upgrade",type:"Mod",done:!0,install:function(b){b.shield++},uninstall:function(b){b.shield--},points:4},{name:"Engine Upgrade",type:"Mod",done:!0,addedaction:"Boost",points:4},{name:"Anti-Pursuit Lasers",type:"Mod",islarge:!0,points:2},{name:"Targeting Computer",
type:"Mod",done:!0,addedaction:"Target",points:2},{name:"Hull Upgrade",type:"Mod",done:!0,install:function(b){b.hull++},uninstall:function(b){b.hull--},points:3},{name:"Munitions Failsafe",type:"Mod",points:1},{name:"Stygium Particle Accelerator",type:"Mod",done:!0,init:function(b){b.resolvecloak=function(){this.focus++;log("[Stygium P.A.] free focus for "+this.name);return Unit.prototype.resolvecloak.call(this)};b.resolveuncloak=function(){this.focus++;log("[Stygium P.A.] free focus for "+this.name);
return Unit.prototype.resolveuncloak.call(this)}},points:2},{name:"Advanced Cloaking Device",type:"Mod",points:4,ship:"TIE Phantom"},{name:"B-Wing/E2",type:"Mod",done:!0,upgrades:["Crew"],points:1,ship:"B-Wing"},{name:"Countermeasures",type:"Mod",islarge:!0,points:3},{name:"Experimental Interface",type:"Mod",unique:!0,points:3},{name:"Tactical Jammer",type:"Mod",islarge:!0,points:1},{name:"Autothrusters",type:"Mod",actionrequired:"Boost",points:2,done:!0,init:function(b){b.adddefensemodd(this,function(b,
d){return this.isinsector(this.m,2,activeunit)?!1:!0}.bind(b),function(b,d){return 0<d-Math.floor(b/10)%10-b%10?(log("[Autothrusters] 1 <p class='blank'></p> -> 1 <p class='evade'></p>"),b+1):b},!1," ")}},{name:"Slave I",type:"Title",unique:!0,points:0,done:!0,ship:"Firespray-31",upgrades:["Torpedo"]},{name:"Millennium Falcon",type:"Title",done:!0,addedaction:"Evade",unique:!0,points:1,ship:"YT-1300"},{name:"Moldy Crow",type:"Title",init:function(b){b.endround=function(){this.evade=0;0<this.focus&&
log("["+this.name+"] keeps focus tokens");this.showinfo()}},unique:!0,done:!0,points:3,ship:"HWK-290"},{name:"ST-321",type:"Title",done:!0,init:function(b){var c=b.candotarget;b.candotarget=function(){c.call(this);return!0};b.resolvetarget=function(){var b,c=[];for(b=0;b<squadron.length;b++)squadron[b].team!=this.team&&c.push(squadron[b]);return 0<c.length?(log("[ST-321] can target any unit on area"),this.resolveactionselection(c,function(b){this.addtarget(c[b]);this.endaction()}.bind(this)),!0):
!1}},unique:!0,points:3,ship:"Lambda-Class Shuttle"},{name:"Royal Guard TIE",type:"Title",done:!0,upgrades:["Mod"],skillmin:5,points:0,ship:"TIE Interceptor"},{name:"A-Wing Test Pilot",type:"Title",done:!0,upgrades:["Elite"],skillmin:2,points:0,ship:"A-Wing",special_case:"A-Wing Test Pilot"},{name:"Outrider",type:"Title",done:!0,init:function(b){var c;for(c=0;c<b.weapons.length;c++)if("Cannon"==b.weapons[c].type){b.weapons[0].isactive=!1;log("["+this.name+"] setting primary weapon inactive");b.weapons[c].isTurret=
function(){return!0};log("["+this.name+"] can fire in 360 degrees");break}},unique:!0,points:5,ship:"YT-2400"},{name:"Dauntless",type:"Title",unique:!0,points:2,ship:"VT-49 Decimator"},{name:"Virago",type:"Title",done:!0,upgrades:["Illicit","System"],unique:!0,points:1,skillmin:4,ship:"StarViper"},{name:"'Heavy Scyk' Interceptor",done:!0,upgrades:["Cannon|Torpedo|Missile"],type:"Title",points:2,ship:"M3-A Interceptor"},{name:"IG-2000",type:"Title",points:0,ship:"Aggressor"},{name:"BTL-A4 Y-Wing",
type:"Title",done:!0,init:function(b){var c;for(c=0;c<b.weapons.length&&"Turret"!=b.weapons[c].type;c++);c!=b.weapons.length&&(b.weapons[c].isTurret=function(){return!1},b.isTurret=function(d){return d==b.weapons[c]?!1:Unit.prototype.isTurret(d)},b.endattack=function(b,c){var f;Unit.prototype.endattack.call(this,b,c);for(f=0;f<this.weapons.length&&"Turret"!=this.weapons[f].type;f++);f<this.weapons.length&&2>this.hasfired&&this.weapons[this.activeweapon].isprimary&&(log("[BTL-A4 Y-Wing] "+this.name+
" attacks again with secondary weapon"),this.selecttargetforattack(f))})},points:0,ship:"Y-Wing"},{name:"Andrasta",type:"Title",done:!0,upgrades:["Bomb","Bomb"],unique:!0,points:0,ship:"Firespray-31"},{name:"TIE/x1",type:"Title",done:!0,upgrades:["System"],pointsupg:-4,points:0,ship:"TIE Advanced"}];
