var UPGRADE_dict={
    "turret":"Turret",
    "ioncannonturret":"Ion Cannon Turret",
    "blasterturret":"Blaster Turret",
    "autoblasterturret":"Autoblaster Turret",
    "torpedo":"Torpedo",
    "protontorpedoes":"Proton Torpedoes",
    "advancedprotontorpedoes":"Advanced Proton Torpedoes",
    "flechettetorpedoes":"Flechette Torpedoes",
    "iontorpedoes":"Ion Torpedoes",
    "bombloadout":"Bomb Loadout",
    "amd":"Astromech Droid",
    "r2astromech":"R2 Astromech",
    "r2d2":"R2-D2",
    "r2f2":"R2-F2",
    "r5d8":"R5-D8",
    "r5k6":"R5-K6",
    "r5astromech":"R5 Astromech",
    "r7astromech":"R7 Astromech",
    "r7t1":"R7-T1",
    "r3a2":"R3-A2",
    "r2d6":"R2-D6",
    "r4d6":"R4-D6",
    "r5p9":"R5-P9",
    "ept":"Elite Pilot Talent",
    "determination":"Determination",
    "swarmtactics":"Swarm Tactics",
    "squadleader":"Squad Leader",
    "experthandling":"Expert Handling",
    "marksmanship":"Marksmanship",
    "daredevil":"Daredevil",
    "elusiveness":"Elusiveness",
    "pushthelimit":"Push the Limit",
    "deadeye":"Deadeye",
    "expose":"Expose",
    "veteraninstincts":"Veteran Instincts",
    "drawtheirfire":"Draw Their Fire",
    "adrenalinerush":"Adrenaline Rush",
    "opportunist":"Opportunist",
    "wingman":"Wingman",
    "decoy":"Decoy",
    "outmaneuver":"Outmaneuver",
    "predator":"Predator",
    "stayontarget":"Stay On Target",
    "lonewolf":"Lone Wolf",
    "ruthlessness":"Ruthlessness",
    "intimidation":"Intimidation",
    "bodyguard":"Bodyguard",
    "missile":"Missile",
    "concussionmissiles":"Concussion Missiles",
    "clustermissiles":"Cluster Missiles",
    "homingmissiles":"Homing Missiles",
    "assaultmissiles":"Assault Missiles",
    "ionpulsemissiles":"Ion Pulse Missiles",
    "chardaanrefit":"Chardaan Refit",
    "protonrockets":"Proton Rockets",
    "crew":"Crew",
    "gunner":"Gunner",
    "mercenarycopilot":"Mercenary Copilot",
    "weaponsengineer":"Weapons Engineer",
    "lukeskywalker":"Luke Skywalker",
    "niennunb":"Nien Nunb",
    "chewbacca":"Chewbacca",
    "reconspecialist":"Recon Specialist",
    "saboteur":"Saboteur",
    "intelligenceagent":"Intelligence Agent",
    "darthvader":"Darth Vader",
    "rebelcaptive":"Rebel Captive",
    "flightinstructor":"Flight Instructor",
    "navigator":"Navigator",
    "tactician":"Tactician",
    "r2d2":"R2-D2",
    "c3po":"C-3PO",
    "kylekatarn":"Kyle Katarn",
    "janors":"Jan Ors",
    "torynfarr":"Toryn Farr",
    "wed15repairdroid":"WED-15 Repair Droid",
    "carlistrieekan":"Carlist Rieekan",
    "jandodonna":"Jan Dodonna",
    "hansolo":"Han Solo",
    "leiaorgana":"Leia Organa",
    "targetingcoordinator":"Targeting Coordinator",
    "raymusantilles":"Raymus Antilles",
    "landocalrissian":"Lando Calrissian",
    "marajade":"Mara Jade",
    "fleetofficer":"Fleet Officer",
    "dashrendar":"Dash Rendar",
    "leebo":"'Leebo'",
    "ysanneisard":"Ysanne Isard",
    "moffjerjerrod":"Moff Jerjerrod",
    "greedo":"Greedo",
    "k4securitydroid":"K4 Security Droid",
    "outlawtech":"Outlaw Tech",
    "cannon":"Cannon",
    "manglercannon":'"Mangler" Cannon',
    "ioncannon":"Ion Cannon",
    "heavylasercannon":"Heavy Laser Cannon",
    "autoblaster":"Autoblaster",
    "bomb":"Bomb",
    "seismiccharges":"Seismic Charges",
    "proximitymines":"Proximity Mines",
    "protonbombs":"Proton Bombs",
    "system":"System",
    "firecontrolsystem":"Fire-Control System",
    "advancedsensors":"Advanced Sensors",
    "sensorjammer":"Sensor Jammer",
    "enhancedscopes":"Enhanced Scopes",
    "accuracycorrector":"Accuracy Corrector",
    "advancedtargetingcomputer":"Advanced Targeting Computer",
    "cargo":"Cargo",
    "commsbooster":"Comms Booster",
    "slicertools":"Slicer Tools",
    "shieldprojector":"Shield Projector",
    "tibannagassupplies":"Tibanna Gas Supplies",
    "ionizationreactor":"Ionization Reactor",
    "enginebooster":"Engine Booster",
    "expandedcargohold":"Expanded Cargo Hold",
    "backupshieldgenerator":"Backup Shield Generator",
    "ememitter":"EM Emitter",
    "frequencyjammer":"Frequency Jammer",
    "hardpoint":"Hardpoint",
    "singleturbolasers":"Single Turbolasers",
    "quadlasercannons":"Quad Laser Cannons",
    "team":"Team",
    "gunneryteam":"Gunnery Team",
    "sensorteam":"Sensor Team",
    "engineeringteam":"Engineering Team",
    "illicit":"Illicit",
    "inertialdampeners":"Inertial Dampeners",
    "deadmansswitch":"Dead Man's Switch",
    "feedbackarray":"Feedback Array",
    "hotshotblaster":"'Hot Shot' Blaster",
    "samd":"Salvaged Astromech Droid",
    "salvagedastromech":"Salvaged Astromech",
    "genius":"'Genius'",
    "unhingedastromech":"Unhinged Astromech",
    "r4b11":"R4-B11",
    "r4agromech":"R4 Agromech",
    "mod":"Modification",
    "stealthdevice":"Stealth Device",
    "shieldupgrade":"Shield Upgrade",
    "engineupgrade":"Engine Upgrade",
    "antipursuitlasers":"Anti-Pursuit Lasers",
    "targetingcomputer":"Targeting Computer",
    "hullupgrade":"Hull Upgrade",
    "munitionsfailsafe":"Munitions Failsafe",
    "stygiumparticleaccelerator":"Stygium Particle Accelerator",
    "advancedcloakingdevice":"Advanced Cloaking Device",
    "combatretrofit":"Combat Retrofit",
    "bwinge2":"B-Wing/E2",
    "countermeasures":"Countermeasures",
    "experimentalinterface":"Experimental Interface",
    "tacticaljammer":"Tactical Jammer",
    "autothrusters":"Autothrusters",
    "title":"Title",
    "slavei":"Slave I",
    "millenniumfalcon":"Millennium Falcon",
    "moldycrow":"Moldy Crow",
    "st321":"ST-321",
    "royalguardtie":"Royal Guard TIE",
    "dodonnaspride":"Dodonna's Pride",
    "awingtestpilot":"A-Wing Test Pilot",
    "tantiveiv":"Tantive IV",
    "brighthope":"Bright Hope",
    "quantumstorm":"Quantum Storm",
    "dutyfree":"Dutyfree",
    "jainaslight":"Jaina's Light",
    "outrider":"Outrider",
    "dauntless":"Dauntless",
    "virago":"Virago",
    "heavyscykinterceptor":"'Heavy Scyk' Interceptor",
    "ig2000":"IG-2000",
    "btla4ywing":"BTL-A4 Y-Wing",
    "andrasta":"Andrasta",
    "tiex1":"TIE/x1"
}
var PILOT_dict={
    "rebels":"Rebel Alliance",
    "xwing":"X-Wing",
    "wedgeantilles":"Wedge Antilles",
    "garvendreis":"Garven Dreis",
    "redsquadronpilot":"Red Squadron Pilot",
    "rookiepilot":"Rookie Pilot",
    "biggsdarklighter":"Biggs Darklighter",
    "lukeskywalker":"Luke Skywalker",
    "wesjanson":"Wes Janson",
    "jekporkins":"Jek Porkins",
    "hobbieklivian":"'Hobbie' Klivian",
    "tarnmison":"Tarn Mison",
    "ywing":"Y-Wing",
    "graysquadronpilot":"Gray Squadron Pilot",
    "dutchvander":"'Dutch' Vander",
    "hortonsalm":"Horton Salm",
    "goldsquadronpilot":"Gold Squadron Pilot",
    "awing":"A-Wing",
    "tychocelchu":"Tycho Celchu",
    "arvelcrynyd":"Arvel Crynyd",
    "greensquadronpilot":"Green Squadron Pilot",
    "prototypepilot":"Prototype Pilot",
    "jakefarrell":"Jake Farrell",
    "gemmersojan":"Gemmer Sojan",
    "yt1300":"YT-1300",
    "outerrimsmuggler":"Outer Rim Smuggler",
    "chewbacca":"Chewbacca",
    "landocalrissian":"Lando Calrissian",
    "hansolo":"Han Solo",
    "bwing":"B-Wing",
    "tennumb":"Ten Numb",
    "ibtisam":"Ibtisam",
    "daggersquadronpilot":"Dagger Squadron Pilot",
    "bluesquadronpilot":"Blue Squadron Pilot",
    "keyanfarlander":"Keyan Farlander",
    "neradantels":"Nera Dantels",
    "hwk290":"HWK-290",
    "rebeloperative":"Rebel Operative",
    "roarkgarnet":"Roark Garnet",
    "kylekatarn":"Kyle Katarn",
    "janors":"Jan Ors",
    "gr75mediumtransport":"GR-75 Medium Transport",
    "gr75mediumtransport":"GR-75 Medium Transport",
    "z95headhunter":"Z-95 Headhunter",
    "banditsquadronpilot":"Bandit Squadron Pilot",
    "talasquadronpilot":"Tala Squadron Pilot",
    "lieutenantblount":"Lieutenant Blount",
    "airencracken":"Airen Cracken",
    "ewing":"E-Wing",
    "knavesquadronpilot":"Knave Squadron Pilot",
    "blackmoonsquadronpilot":"Blackmoon Squadron Pilot",
    "etahnabaht":"Etahn A'baht",
    "corranhorn":"Corran Horn",
    "cr90corvette":"CR90 Corvette",
    "cr90corvettefore":"CR90 Corvette (Fore)",
    "cr90corvetteaft":"CR90 Corvette (Aft)",
    "yt2400":"YT-2400",
    "wildspacefringer":"Wild Space Fringer",
    "eadenvrill":"Eaden Vrill",
    "leebo":"'Leebo'",
    "dashrendar":"Dash Rendar",
    "empire":"Galactic Empire",
    "tiefighter":"TIE Fighter",
    "academypilot":"Academy Pilot",
    "obsidiansquadronpilot":"Obsidian Squadron Pilot",
    "blacksquadronpilot":"Black Squadron Pilot",
    "wingedgundark":"'Winged Gundark'",
    "nightbeast":"'Night Beast'",
    "backstabber":'"Backstabber"',
    "darkcurse":'"Dark Curse"',
    "maulermithel":'"Mauler Mithel"',
    "howlrunner":'"Howlrunner"',
    "tieadvanced":"TIE Advanced",
    "maarekstele":"Maarek Stele",
    "tempestsquadronpilot":"Tempest Squadron Pilot",
    "stormsquadronpilot":"Storm Squadron Pilot",
    "darthvader":"Darth Vader",
    "commanderalozen":"Commander Alozen",
    "tieinterceptor":"TIE Interceptor",
    "alphasquadronpilot":"Alpha Squadron Pilot",
    "avengersquadronpilot":"Avenger Squadron Pilot",
    "sabersquadronpilot":"Saber Squadron Pilot",
    "felswrath":"'Fel's Wrath'",
    "turrphennir":"Turr Phennir",
    "soontirfel":"Soontir Fel",
    "lieutenantlorrir":"Lieutenant Lorrir",
    "royalguardpilot":"Royal Guard Pilot",
    "tetrancowall":"Tetran Cowall",
    "kirkanos":"Kir Kanos",
    "carnorjax":"Carnor Jax",
    "firespray31":"Firespray-31",
    "kathscarlet":"Kath Scarlet",
    "bobafett":"Boba Fett",
    "krassistrelix":"Krassis Trelix",
    "bountyhunter":"Bounty Hunter",
    "tiebomber":"TIE Bomber",
    "scimitarsquadronpilot":"Scimitar Squadron Pilot",
    "gammasquadronpilot":"Gamma Squadron Pilot",
    "captainjonus":"Captain Jonus",
    "majorrhymer":"Major Rhymer",
    "lambdaclassshuttle":"Lambda-Class Shuttle",
    "captainkagi":"Captain Kagi",
    "coloneljendon":"Colonel Jendon",
    "captainyorr":"Captain Yorr",
    "omicrongrouppilot":"Omicron Group Pilot",
    "tiedefender":"TIE Defender",
    "deltasquadronpilot":"Delta Squadron Pilot",
    "onyxsquadronpilot":"Onyx Squadron Pilot",
    "colonelvessery":"Colonel Vessery",
    "rexlerbrath":"Rexler Brath",
    "tiephantom":"TIE Phantom",
    "sigmasquadronpilot":"Sigma Squadron Pilot",
    "shadowsquadronpilot":"Shadow Squadron Pilot",
    "echo":"'Echo'",
    "whisper":"'Whisper'",
    "vt49decimator":"VT-49 Decimator",
    "patrolleader":"Patrol Leader",
    "captainoicunn":"Captain Oicunn",
    "commanderkenkirk":"Commander Kenkirk",
    "rearadmiralchiraneau":"Rear Admiral Chiraneau",
    "scum":"Scum and Villainy",
    "starviper":"StarViper",
    "princexizor":"Prince Xizor",
    "guri":"Guri",
    "blacksunvigo":"Black Sun Vigo",
    "blacksunenforcer":"Black Sun Enforcer",
    "m3ainterceptor":"M3-A Interceptor",
    "serissu":"Serissu",
    "aggressor":"Aggressor",
    "ig88d":"IG-88D",
    "z95headhunter":"Z-95 Headhunter",
    "ndrusuhlak":"N'Dru Suhlak",
    "kaatoleeachos":"Kaa'To Leeachos",
    "blacksunsoldier":"Black Sun Soldier",
    "binayrepirate":"Binayre Pirate",
    "firespray31":"Firespray-31",
    "bobafett":"Boba Fett",
    "kathscarlet":"Kath Scarlet",
    "emonazzameen":"Emon Azzameen",
    "mandalorianmercenary":"Mandalorian Mercenary",
    "ywing":"Y-Wing",
    "kavil":"Kavil",
    "drearenthal":"Drea Renthal",
    "syndicatethug":"Syndicate Thug",
    "hwk290":"HWK-290",
    "dacebonearm":"Dace Bonearm",
    "palobgodalhi":"Palob Godalhi",
    "torkilmux":"Torkil Mux"
};
